package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"
)

// ── Embedded content ──────────────────────────────────────────────────────────

const pfAnchorContent = `# =============================================================
# Soft blocklist for the "agent" user
# Block known-bad ports/protocols; allow everything else
# Generated by sandbox setup
# =============================================================

# --- Block exfiltration / C2 protocols ---

# SMTP (email exfiltration)
block return out quick proto tcp from any to any port { 25, 465, 587 } user agent

# IRC (C2 channel)
block return out quick proto tcp from any to any port { 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6697 } user agent

# FTP (legacy file transfer)
block return out quick proto tcp from any to any port { 20, 21 } user agent

# Telnet (insecure remote access)
block return out quick proto tcp from any to any port 23 user agent

# SMB (lateral movement)
block return out quick proto tcp from any to any port 445 user agent

# RDP (remote desktop)
block return out quick proto tcp from any to any port 3389 user agent

# VNC (remote desktop)
block return out quick proto tcp from any to any port { 5900, 5901 } user agent

# Tor (anonymous exfiltration)
block return out quick proto tcp from any to any port { 9050, 9150 } user agent

# SOCKS proxy
block return out quick proto tcp from any to any port 1080 user agent

# VPN protocols
block return out quick proto tcp from any to any port { 1194, 1723 } user agent
block return out quick proto udp from any to any port { 1194, 1723, 4500 } user agent

# XMPP (messaging / C2)
block return out quick proto tcp from any to any port { 5222, 5269 } user agent

# --- Block ICMP tunneling ---
block return out quick proto icmp from any to any user agent

# --- Allow everything else ---
pass out quick user agent
`

const pfDaemonPlistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.local.pf-agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>/sbin/pfctl</string>
        <string>-f</string>
        <string>/etc/pf.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/pf-agent.log</string>
</dict>
</plist>
`

// pfConfAddition is appended to /etc/pf.conf to register the anchor.
// Leading newline provides a blank-line separator from existing content.
const pfConfAddition = `
# Claude Code sandbox user blocklist
anchor "agent"
load anchor "agent" from "/etc/pf.anchors/agent"
`

// seatbeltProfileContent is the SBPL policy written to seatbeltProfilePath.
// It is loaded at Claude launch time via sandbox-exec.  Parameters must be
// supplied by the wrapper script:
//
//	HOME           — agent home directory (/Users/agent)
//	WORKSPACE_ROOT — host workspace root (for read-only reference access)
//	PROJECT_DIR    — active project directory (read/write)
//	TMPDIR         — temp directory (/private/tmp)
const seatbeltProfileContent = `;; Claude Code runtime seatbelt profile.
;; Installed by sandbox setup — do not edit manually.
;; To update: rm /Users/agent/.config/sandbox/claude.sb && sandbox setup
;;
;; Required parameters (pass via sandbox-exec -D KEY=VALUE):
;;   HOME           - agent home dir  (e.g. /Users/agent)
;;   WORKSPACE_ROOT - workspace root  (e.g. /Users/dr/workspace)
;;   PROJECT_DIR    - active project  (e.g. /Users/dr/workspace/myproject)
;;   TMPDIR         - temp dir (e.g. /private/tmp)

(version 1)
(deny default)

;; ── Process execution ─────────────────────────────────────────────────────────
(allow process-exec (subpath "/usr/bin"))
(allow process-exec (subpath "/bin"))
(allow process-exec (subpath "/usr/local"))
(allow process-exec (subpath "/opt/homebrew"))
(allow process-exec (subpath (param "HOME")))
(allow process-fork)
(allow process-info* (target same-sandbox))
(allow signal (target same-sandbox))

;; ── System libraries (required by Node.js) ────────────────────────────────────
(allow file-read* (subpath "/usr/lib"))
(allow file-read* (subpath "/usr/share"))
(allow file-read* (subpath "/System/Library"))
(allow file-read* (subpath "/Library/Frameworks"))
(allow file-read* (subpath "/private/etc"))
(allow file-read* (literal "/dev/urandom"))
(allow file-read* (literal "/dev/null"))
(allow file-read* (literal "/dev/zero"))
(allow file-write* (literal "/dev/null"))
(allow file-read* (subpath "/usr/local"))
(allow file-read* (subpath "/opt/homebrew"))

;; ── Workspace root — read-only access for reference repos ────────────────────
(allow file-read* (subpath (param "WORKSPACE_ROOT")))

;; ── Active project — full read/write ──────────────────────────────────────────
(allow file-read* (subpath (param "PROJECT_DIR")))
(allow file-write* (subpath (param "PROJECT_DIR")))

;; ── Claude config (auth tokens, settings, model cache) ────────────────────────
(allow file-read* (subpath (string-append (param "HOME") "/.claude")))
(allow file-write* (subpath (string-append (param "HOME") "/.claude")))

;; ── Claude installation (binary + node_modules) ───────────────────────────────
(allow file-read* (subpath (string-append (param "HOME") "/.local")))
(allow file-write* (subpath (string-append (param "HOME") "/.local")))

;; ── Git config (needed for commit operations) ─────────────────────────────────
(allow file-read* (literal (string-append (param "HOME") "/.gitconfig")))
(allow file-read* (subpath (string-append (param "HOME") "/.config/git")))

;; ── Shell rc files (read-only; needed at login) ───────────────────────────────
(allow file-read* (literal (string-append (param "HOME") "/.zshrc")))
(allow file-read* (literal (string-append (param "HOME") "/.zprofile")))
(allow file-read* (literal (string-append (param "HOME") "/.bashrc")))
(allow file-read* (literal (string-append (param "HOME") "/.bash_profile")))

;; ── npm / node cache ──────────────────────────────────────────────────────────
(allow file-read* file-write* (subpath (string-append (param "HOME") "/.npm")))

;; ── XDG / toolchain state under agent home ──────────────────────────────────
(allow file-read* file-write* (subpath (string-append (param "HOME") "/.cache")))
(allow file-read* file-write* (subpath (string-append (param "HOME") "/.config")))
(allow file-read* file-write* (subpath (string-append (param "HOME") "/.local/share")))
(allow file-read* file-write* (subpath (string-append (param "HOME") "/Library/Caches")))

;; ── Temp and cache directories ────────────────────────────────────────────────
(allow file-read* file-write* (subpath (param "TMPDIR")))
(allow file-read* file-write* (subpath "/private/tmp"))
(allow file-read* file-write* (subpath "/private/var/folders"))

;; ── Terminal support (Node.js requires these) ─────────────────────────────────
(allow pseudo-tty)
(allow file-ioctl)
(allow file-read* file-write* (literal "/dev/ptmx"))
(allow file-read* file-write* (regex #"/dev/ttys[0-9]+"))

;; ── Mach services ─────────────────────────────────────────────────────────────
(allow mach-lookup (global-name "com.apple.system.logger"))
(allow mach-lookup (global-name "com.apple.CoreServices.coreservicesd"))
(allow mach-lookup (global-name "com.apple.system.notification_center"))
(allow mach-lookup (global-name "com.apple.mDNSResponder"))
(allow mach-host*)

;; ── Network: outbound for Anthropic API calls ─────────────────────────────────
(allow network-outbound)
(allow network-inbound (local tcp "*:*"))

;; ── DENY sensitive credential directories ─────────────────────────────────────
;; These appear last so they override the broad allows above (last match wins).
(deny file-read* (subpath (string-append (param "HOME") "/.ssh")))
(deny file-read* (subpath (string-append (param "HOME") "/.aws")))
(deny file-read* (subpath (string-append (param "HOME") "/.gnupg")))
(deny file-read* (subpath (string-append (param "HOME") "/Library/Keychains")))
(deny file-read* (subpath (string-append (param "HOME") "/.config/gh")))
`

// seatbeltWrapperContent is the launch wrapper installed at seatbeltWrapperPath.
// It enforces seatbelt confinement every time Claude is started as the agent user.
const seatbeltWrapperContent = `#!/bin/bash
# claude-sandboxed — launch Claude Code under seatbelt confinement.
# Installed by sandbox setup — do not edit manually.
#
# Usage:
#   claude-sandboxed [PROJECT_DIR] [claude-args...]
#
# If the first argument is an existing directory it is used as PROJECT_DIR;
# otherwise $PWD is used and all arguments are forwarded to claude.
#
# If SANDBOX_WORKSPACE_ROOT is set (for example by agent-shell / claude-sandbox),
# it is passed through so sibling repos under ~/workspace stay readable.
set -euo pipefail

PROFILE=/Users/agent/.config/sandbox/claude.sb
CLAUDE_BIN=/Users/agent/.local/bin/claude
export PATH="/Users/agent/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export TMPDIR="${TMPDIR:-/private/tmp}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export HOMEBREW_NO_AUTO_UPDATE="${HOMEBREW_NO_AUTO_UPDATE:-1}"

if [[ ! -f "$PROFILE" ]]; then
    printf 'error: seatbelt profile not found: %s\n' "$PROFILE" >&2
    printf 'Run "sandbox setup" to install it.\n' >&2
    exit 1
fi

if [[ ! -f "$CLAUDE_BIN" ]]; then
    printf 'error: claude binary not found: %s\n' "$CLAUDE_BIN" >&2
    exit 1
fi

# Resolve PROJECT_DIR from first arg if it looks like a directory.
if [[ $# -gt 0 && -d "$1" ]]; then
    PROJECT_DIR="$1"
    shift
else
    PROJECT_DIR="${PROJECT_DIR:-$PWD}"
fi

WORKSPACE_ROOT="${SANDBOX_WORKSPACE_ROOT:-${WORKSPACE_ROOT:-$PROJECT_DIR}}"

exec /usr/bin/sandbox-exec \
    -D "HOME=$HOME" \
    -D "WORKSPACE_ROOT=$WORKSPACE_ROOT" \
    -D "PROJECT_DIR=$PROJECT_DIR" \
    -D "TMPDIR=$TMPDIR" \
    -f "$PROFILE" \
    "$CLAUDE_BIN" "$@"
`

const hostsBlocklistContent = `
# === AI Agent Blocklist ===
# Tunnel services
0.0.0.0 ngrok.io
0.0.0.0 ngrok.com
0.0.0.0 ngrok-free.app
0.0.0.0 tunnel.cloudflare.com
0.0.0.0 trycloudflare.com
0.0.0.0 serveo.net
0.0.0.0 localtunnel.me
0.0.0.0 localhost.run
0.0.0.0 localxpose.io
0.0.0.0 pagekite.me
0.0.0.0 bore.digital
0.0.0.0 localtonet.com
0.0.0.0 zrok.io
0.0.0.0 devtunnels.ms
0.0.0.0 loca.lt
0.0.0.0 tunnelmole.com
0.0.0.0 playit.gg
0.0.0.0 pinggy.io
0.0.0.0 lokal.so
0.0.0.0 telebit.cloud
0.0.0.0 loophole.cloud
# Paste services
0.0.0.0 pastebin.com
0.0.0.0 paste.ee
0.0.0.0 ghostbin.com
0.0.0.0 hastebin.com
0.0.0.0 dpaste.org
0.0.0.0 justpaste.it
0.0.0.0 rentry.co
0.0.0.0 ix.io
# File sharing
0.0.0.0 transfer.sh
0.0.0.0 file.io
0.0.0.0 gofile.io
0.0.0.0 catbox.moe
0.0.0.0 filebin.net
# Webhook capture
0.0.0.0 webhook.site
0.0.0.0 requestbin.com
0.0.0.0 pipedream.com
0.0.0.0 hookbin.com
0.0.0.0 beeceptor.com
# === End AI Agent Blocklist ===
`

// ── Command ───────────────────────────────────────────────────────────────────

func newSetupCmd() *cobra.Command {
	var agentUIDFlag, sharedGIDFlag string
	cmd := &cobra.Command{
		Use:   "setup",
		Short: "Configure the macOS sandbox (Option A: dedicated agent user + pf firewall)",
		Long: `Configure the macOS sandbox: dedicated agent user, workspace-root ACLs, pf port
blocklist, DNS blocklist, seatbelt profile, and host-side command wrappers.

Interactive by default — prompts for confirmation before making any changes.
For scripted or autonomous use, pass --yes to answer all prompts automatically:

  sandbox setup --yes
  sandbox setup --yes --agent-uid 601 --group-gid 601

Use --dry-run to preview all commands without executing anything.`,
	}
	cmd.Flags().StringVar(&agentUIDFlag, "agent-uid", "",
		"Override UID for the agent user (default: 599; use when 599 is already taken)")
	cmd.Flags().StringVar(&sharedGIDFlag, "group-gid", "",
		"Override GID for the dev group (default: 599; use when 599 is already taken)")
	cmd.RunE = func(c *cobra.Command, args []string) error {
		if agentUIDFlag != "" {
			agentUID = agentUIDFlag
		}
		if sharedGIDFlag != "" {
			sharedGID = sharedGIDFlag
		}
		return runSetup(c, args)
	}
	return cmd
}

// newStatusCmd exposes verifySetup as a standalone command for quick health
// checks.  Returns exit code 1 when any critical check fails so callers
// (scripts, Claude, CI) can test whether the sandbox is ready.
func newStatusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Check sandbox health (quick invariant check, no changes)",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			ui := &UI{}
			verifySetup(ui)
			if ui.Summary() {
				return fmt.Errorf("sandbox is not fully configured")
			}
			return nil
		},
	}
}

// runSetup is the top-level entry point.  Named return so defer can inspect
// retErr and print the rollback hint — equivalent to shell's "trap ... ERR".
func runSetup(_ *cobra.Command, _ []string) (retErr error) {
	ui := &UI{DryRun: flagDryRun, YesAll: flagYesAll}
	r := NewRunner(ui, flagVerbose, flagDryRun)

	if err := checkPlatform(); err != nil {
		ui.Fatal(err.Error())
	}

	cu, err := user.Current()
	if err != nil {
		return fmt.Errorf("cannot determine current user: %w", err)
	}
	if cu.Username == "root" {
		ui.Fatal("Run as your normal user, not root. The tool uses sudo where needed.")
	}

	ui.Banner(cu.Username)

	if flagDryRun {
		cYellow.Println("  ────────────────────────────────────────────────────")
		cYellow.Println("  DRY RUN — no changes will be made.")
		cYellow.Println("  Shows all commands regardless of current system state.")
		cYellow.Println("  Steps already complete are skipped when run for real.")
		cYellow.Println("  ────────────────────────────────────────────────────")
		fmt.Println()
	} else if !ui.YesAll && !ui.IsInteractive() {
		// Non-TTY without --yes: fail fast with an actionable message rather
		// than silently aborting after the Ask prompt returns false.
		return fmt.Errorf("stdin is not a terminal\nFor non-interactive setup run: sandbox setup --yes")
	} else if !ui.Ask("Proceed with setup?") {
		fmt.Println("  Aborted.")
		return nil
	}

	defer func() {
		if retErr != nil && !flagDryRun {
			fmt.Fprintln(os.Stderr)
			cRed.Fprintln(os.Stderr, "Setup interrupted — some steps may be incomplete.")
			fmt.Fprintln(os.Stderr, "See setup-option-a.md § Uninstall / Rollback")
		}
	}()

	if err := setupAgentUser(ui, r); err != nil {
		return err
	}
	if err := setupDevGroup(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupSharedWorkspace(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupBackupScope(ui, r); err != nil {
		return err
	}
	if err := setupHardeningGaps(ui, r); err != nil {
		return err
	}
	if err := setupSeatbelt(ui, r); err != nil {
		return err
	}
	if err := setupUserExperience(ui, r); err != nil {
		return err
	}
	if err := setupSudoers(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupPfFirewall(ui, r); err != nil {
		return err
	}
	if err := setupDNSBlocklist(ui, r); err != nil {
		return err
	}
	if err := setupLaunchDaemon(ui, r); err != nil {
		return err
	}

	verifySetup(ui)

	if !flagDryRun {
		ui.DoneBox(cu.Username)
	}
	return nil
}

// ── Step 1: Agent user ────────────────────────────────────────────────────────

func setupAgentUser(ui *UI, r *Runner) error {
	ui.Step(fmt.Sprintf("Create '%s' user", agentUser))

	if u, err := user.Lookup(agentUser); err == nil {
		ui.SkipDone(fmt.Sprintf("User '%s' already exists (uid=%s)", agentUser, u.Uid))
		return nil
	}

	if taken, err := uidTaken(agentUID); err != nil {
		return fmt.Errorf("check UID: %w", err)
	} else if taken {
		return fmt.Errorf("UID %s is already taken — use: sandbox setup --agent-uid <different-uid>", agentUID)
	}

	record := "/Users/" + agentUser
	for _, args := range [][]string{
		{"dscl", ".", "-create", record},
		{"dscl", ".", "-create", record, "UserShell", "/bin/zsh"},
		{"dscl", ".", "-create", record, "UniqueID", agentUID},
		{"dscl", ".", "-create", record, "PrimaryGroupID", "20"},
		{"dscl", ".", "-create", record, "NFSHomeDirectory", agentHome},
	} {
		if err := r.Sudo(args...); err != nil {
			return fmt.Errorf("dscl %v: %w", args[2:], err)
		}
	}
	ui.Ok("User record created")

	if err := r.Sudo("mkdir", "-p", agentHome); err != nil {
		return fmt.Errorf("mkdir %s: %w", agentHome, err)
	}
	if err := r.Sudo("chown", agentUser+":staff", agentHome); err != nil {
		return fmt.Errorf("chown %s: %w", agentHome, err)
	}
	// createhomedir may exit non-zero even on success; ignore the error.
	r.Sudo("createhomedir", "-c", "-u", agentUser) //nolint:errcheck
	ui.Ok(fmt.Sprintf("Home directory created at %s", agentHome))

	if err := r.Sudo("dscl", ".", "-create", record, "IsHidden", "1"); err != nil {
		return fmt.Errorf("hide user: %w", err)
	}
	ui.Ok("Hidden from login screen")

	if ui.IsInteractive() {
		fmt.Printf("\n  Set a password for the '%s' user:\n", agentUser)
		if err := r.Interactive("sudo", "passwd", agentUser); err != nil {
			return fmt.Errorf("passwd: %w", err)
		}
		ui.Ok("Password set")
	} else {
		// Non-interactive (--yes, piped stdin, or dry-run): generate a random
		// password.  The agent account is never used for login; this satisfies
		// macOS's requirement that every account has a password hash.
		var password string
		if r.DryRun {
			password = "<random-base64>"
		} else {
			pass, err := exec.Command("openssl", "rand", "-base64", "24").Output()
			if err != nil {
				return fmt.Errorf("generate random password: %w", err)
			}
			password = strings.TrimSpace(string(pass))
		}
		if err := r.Sudo("dscl", ".", "-passwd", "/Users/"+agentUser, password); err != nil {
			return fmt.Errorf("set agent password: %w", err)
		}
		ui.Ok(fmt.Sprintf("Password set for '%s' (random, login is disabled)", agentUser))
	}

	if _, err := user.Lookup(agentUser); err != nil {
		return fmt.Errorf("user '%s' not found after creation: %w", agentUser, err)
	}
	return nil
}

// ── Step 2: Dev group ─────────────────────────────────────────────────────────

func setupDevGroup(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Create '%s' group", sharedGroup))

	if g, err := user.LookupGroup(sharedGroup); err == nil {
		ui.SkipDone(fmt.Sprintf("Group '%s' already exists (gid=%s)", sharedGroup, g.Gid))
	} else {
		if taken, err := gidTaken(sharedGID); err != nil {
			return fmt.Errorf("check GID: %w", err)
		} else if taken {
			return fmt.Errorf("GID %s is already taken — use: sandbox setup --group-gid <different-gid>", sharedGID)
		}

		record := "/Groups/" + sharedGroup
		for _, args := range [][]string{
			{"dscl", ".", "-create", record},
			{"dscl", ".", "-create", record, "PrimaryGroupID", sharedGID},
			{"dscl", ".", "-create", record, "RealName", "Shared dev workspace"},
		} {
			if err := r.Sudo(args...); err != nil {
				return fmt.Errorf("dscl %v: %w", args[2:], err)
			}
		}
		ui.Ok(fmt.Sprintf("Group '%s' created (gid=%s)", sharedGroup, sharedGID))
	}

	for _, u := range []string{currentUser, agentUser} {
		member, err := groupMembershipContains(sharedGroup, u)
		if err != nil {
			return err
		}
		if member {
			ui.SkipDone(fmt.Sprintf("%s is already a member of '%s'", u, sharedGroup))
		} else {
			if err := r.Sudo("dscl", ".", "-append",
				"/Groups/"+sharedGroup, "GroupMembership", u); err != nil {
				return fmt.Errorf("add %s to %s: %w", u, sharedGroup, err)
			}
			ui.Ok(fmt.Sprintf("Added %s to '%s'", u, sharedGroup))
		}
	}
	return nil
}

// ── Step 3: Workspace root ────────────────────────────────────────────────────

func setupSharedWorkspace(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Prepare workspace root at %s", sharedWorkspace))

	if _, err := os.Stat(sharedWorkspace); os.IsNotExist(err) {
		if err := r.MkdirAll(sharedWorkspace, 0o770); err != nil {
			return fmt.Errorf("mkdir %s: %w", sharedWorkspace, err)
		}
		ui.Ok(fmt.Sprintf("Created %s", sharedWorkspace))
	} else {
		ui.SkipDone(fmt.Sprintf("Workspace root exists at %s", sharedWorkspace))
	}

	if err := r.Sudo("chown", currentUser+":"+sharedGroup, sharedWorkspace); err != nil {
		return fmt.Errorf("chown %s: %w", sharedWorkspace, err)
	}
	if err := r.Sudo("chmod", "770", sharedWorkspace); err != nil {
		return fmt.Errorf("chmod 770 %s: %w", sharedWorkspace, err)
	}
	if err := r.Sudo("chmod", "g+s", sharedWorkspace); err != nil {
		return fmt.Errorf("chmod g+s %s: %w", sharedWorkspace, err)
	}
	ui.Ok(fmt.Sprintf("Permissions: 770, setgid, owner %s:%s", currentUser, sharedGroup))

	// The workspace now lives inside the controlling user's home directory.
	// Grant the agent account directory traversal on $HOME so it can reach
	// ~/workspace without opening up the rest of the home directory for listing.
	homeDir := os.Getenv("HOME")
	if homeAllowsAgentTraverse(homeDir) {
		if homeHasAgentTraverseACL(homeDir) {
			ui.SkipDone(fmt.Sprintf("Home directory ACL already lets '%s' traverse to %s", agentUser, workspaceHint))
		} else {
			ui.SkipDone(fmt.Sprintf("Home directory permissions already allow '%s' to reach %s", agentUser, workspaceHint))
		}
	} else {
		if err := r.Sudo("chmod", "+a", homeTraverseACLEntry(), homeDir); err != nil {
			return fmt.Errorf("set home traversal ACL: %w", err)
		}
		ui.Ok(fmt.Sprintf("Home directory ACL set: '%s' can traverse to %s", agentUser, workspaceHint))
	}

	// umask 077 (set for the agent user) clears group bits on newly created files.
	// An inheritable ACL grants the dev group read/write on all files in the workspace
	// regardless of umask, so both principals can collaborate without weakening isolation
	// elsewhere.
	if workspaceHasDevACL() {
		ui.SkipDone(fmt.Sprintf("Workspace ACL already grants '%s' group inherited access", sharedGroup))
	} else {
		aclEntry := "group:" + sharedGroup +
			" allow read,write,execute,append,delete,delete_child," +
			"readattr,writeattr,readextattr,writeextattr,readsecurity," +
			"file_inherit,directory_inherit"
		if err := r.Sudo("chmod", "+a", aclEntry, sharedWorkspace); err != nil {
			return fmt.Errorf("set workspace ACL: %w", err)
		}
		ui.Ok(fmt.Sprintf("Workspace ACL set: '%s' group gets inherited read/write access", sharedGroup))
	}

	legacyLink := os.Getenv("HOME") + "/workspace-shared"
	if info, err := os.Lstat(legacyLink); err == nil && info.Mode()&os.ModeSymlink != 0 {
		ui.WarnMsg(fmt.Sprintf("Legacy symlink %s still exists; remove it if you no longer need the old alias", legacyLink))
	}

	// Symlink from agent user's home
	// asAgentQuiet("test", ...) is a read-only check — bypasses Runner.
	agentLink := agentHome + "/workspace"
	if asAgentQuiet("test", "-L", agentLink) == nil {
		ui.SkipDone(fmt.Sprintf("Symlink %s already exists", agentLink))
	} else if asAgentQuiet("test", "-e", agentLink) == nil {
		ui.WarnMsg(fmt.Sprintf("%s exists but is not a symlink — skipping", agentLink))
	} else {
		if err := r.AsAgent("ln", "-s", sharedWorkspace, agentLink); err != nil {
			return fmt.Errorf("symlink %s: %w", agentLink, err)
		}
		ui.Ok(fmt.Sprintf("Created symlink %s → %s", agentLink, sharedWorkspace))
	}
	return nil
}

// ── Step 3b: Backup scope file ────────────────────────────────────────────────

func setupBackupScope(ui *UI, r *Runner) error {
	ui.Step("Initialize backup scope file")

	if _, err := os.Stat(backupExcludesFile); err == nil {
		ui.SkipDone(fmt.Sprintf("Backup scope file already exists at %s", backupExcludesFile))
		return nil
	}

	if _, err := os.Stat(sharedWorkspace); err != nil {
		ui.WarnMsg(fmt.Sprintf("Workspace root not found (%s) — backup scope file skipped", sharedWorkspace))
		return nil
	}

	if err := r.UserWriteFile(backupExcludesFile, defaultBackupExcludesContent()); err != nil {
		return fmt.Errorf("write backup scope file: %w", err)
	}
	ui.Ok(fmt.Sprintf("Backup scope file created at %s", backupExcludesFile))
	ui.WarnMsg(fmt.Sprintf("Edit %s to list repos you do not want backed up.", backupExcludesFile))
	return nil
}

// ── Step 4: Hardening gaps ────────────────────────────────────────────────────

func setupHardeningGaps(ui *UI, r *Runner) error {
	ui.Step("Harden known macOS isolation gaps")

	// Docker socket — owned by current user, no sudo needed.
	dockerSock := os.Getenv("HOME") + "/.docker/run/docker.sock"
	if info, err := os.Stat(dockerSock); err == nil && info.Mode()&os.ModeSocket != 0 {
		current := info.Mode().Perm()
		if current == 0o700 {
			ui.SkipDone("Docker socket already restricted (700)")
		} else {
			if err := r.Chmod(dockerSock, 0o700); err != nil {
				return fmt.Errorf("chmod docker socket: %w", err)
			}
			ui.Ok(fmt.Sprintf("Docker socket restricted to owner only (was %04o)", current))
		}
	} else {
		ui.SkipDone("Docker socket not found (Docker Desktop not running or not installed)")
	}

	// Restrictive umask for agent user — use a managed block so rollback is precise.
	// asAgentOutput is a read — bypasses Runner.
	agentZshrc := agentHome + "/.zshrc"
	agentZshrcData, _ := asAgentOutput("cat", agentZshrc)
	if strings.Contains(agentZshrcData, umaskBlockStart) {
		ui.SkipDone("umask 077 already set in agent's .zshrc")
	} else {
		updated := upsertManagedBlock(agentZshrcData, umaskBlockStart, umaskBlockEnd, "umask 077")
		if err := r.SudoWriteFile(agentZshrc, updated); err != nil {
			return fmt.Errorf("set umask in agent .zshrc: %w", err)
		}
		if err := r.Sudo("chown", agentUser+":staff", agentZshrc); err != nil {
			return fmt.Errorf("chown agent .zshrc: %w", err)
		}
		ui.Ok("Set umask 077 in agent's .zshrc")
	}

	// Restrictive umask for current user — managed block so rollback only removes ours.
	// os.ReadFile is a read — bypasses Runner.
	userZshrc := os.Getenv("HOME") + "/.zshrc"
	userZshrcData, _ := os.ReadFile(userZshrc)
	if strings.Contains(string(userZshrcData), umaskBlockStart) {
		ui.SkipDone("umask 077 already set in your .zshrc")
	} else if ui.Ask("Add 'umask 077' to your .zshrc? (prevents /tmp leakage)") {
		updated := upsertManagedBlock(string(userZshrcData), umaskBlockStart, umaskBlockEnd, "umask 077")
		if err := r.UserWriteFile(userZshrc, updated); err != nil {
			return fmt.Errorf("write .zshrc: %w", err)
		}
		ui.Ok("Set umask 077 in your .zshrc")
	} else {
		ui.WarnMsg("Skipped. Consider adding 'umask 077' manually.")
	}

	return nil
}

// ── Step 5: Seatbelt profile ──────────────────────────────────────────────────

func setupSeatbelt(ui *UI, r *Runner) error {
	ui.Step("Install seatbelt profile for Claude runtime")

	// Create profile directory as the agent user so ownership is correct.
	if err := r.AsAgent("mkdir", "-p", seatbeltProfileDir); err != nil {
		return fmt.Errorf("mkdir %s: %w", seatbeltProfileDir, err)
	}

	// The profile and wrapper are managed artifacts. Re-write them on every run
	// so setup doubles as an in-place upgrade path when the policy evolves.
	if err := r.SudoWriteFile(seatbeltProfilePath, seatbeltProfileContent); err != nil {
		return fmt.Errorf("write seatbelt profile: %w", err)
	}
	if err := r.Sudo("chown", agentUser+":staff", seatbeltProfilePath); err != nil {
		return fmt.Errorf("chown seatbelt profile: %w", err)
	}
	if err := r.Sudo("chmod", "644", seatbeltProfilePath); err != nil {
		return fmt.Errorf("chmod seatbelt profile: %w", err)
	}
	ui.Ok(fmt.Sprintf("Seatbelt profile installed at %s", seatbeltProfilePath))

	// Ensure ~/.local/bin exists before writing the wrapper.
	wrapperDir := agentHome + "/.local/bin"
	if err := r.AsAgent("mkdir", "-p", wrapperDir); err != nil {
		return fmt.Errorf("mkdir %s: %w", wrapperDir, err)
	}

	if err := r.SudoWriteFile(seatbeltWrapperPath, seatbeltWrapperContent); err != nil {
		return fmt.Errorf("write seatbelt wrapper: %w", err)
	}
	if err := r.Sudo("chown", agentUser+":staff", seatbeltWrapperPath); err != nil {
		return fmt.Errorf("chown seatbelt wrapper: %w", err)
	}
	if err := r.Sudo("chmod", "755", seatbeltWrapperPath); err != nil {
		return fmt.Errorf("chmod seatbelt wrapper: %w", err)
	}
	ui.Ok(fmt.Sprintf("Seatbelt wrapper installed at %s", seatbeltWrapperPath))

	return nil
}

func setupUserExperience(ui *UI, r *Runner) error {
	ui.Step("Install command wrappers and toolchain env")

	for _, dir := range []string{
		defaultAgentCacheHome,
		defaultAgentDataHome,
		agentHome + "/.npm",
	} {
		if err := r.AsAgent("mkdir", "-p", dir); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}

	if err := r.SudoWriteFile(agentEnvPath, agentEnvContent()); err != nil {
		return fmt.Errorf("write agent env file: %w", err)
	}
	if err := r.Sudo("chown", agentUser+":staff", agentEnvPath); err != nil {
		return fmt.Errorf("chown agent env file: %w", err)
	}
	if err := r.Sudo("chmod", "644", agentEnvPath); err != nil {
		return fmt.Errorf("chmod agent env file: %w", err)
	}
	ui.Ok(fmt.Sprintf("Agent toolchain env written to %s", agentEnvPath))

	agentZshrc := agentHome + "/.zshrc"
	agentZshrcData, _ := asAgentOutput("cat", agentZshrc)
	updatedAgentZshrc := upsertManagedBlock(agentZshrcData,
		agentShellBlockStart,
		agentShellBlockEnd,
		`[[ -f "$HOME/.config/sandbox/agent-env.zsh" ]] && source "$HOME/.config/sandbox/agent-env.zsh"`,
	)
	if err := r.SudoWriteFile(agentZshrc, updatedAgentZshrc); err != nil {
		return fmt.Errorf("update %s: %w", agentZshrc, err)
	}
	if err := r.Sudo("chown", agentUser+":staff", agentZshrc); err != nil {
		return fmt.Errorf("chown %s: %w", agentZshrc, err)
	}
	ui.Ok(fmt.Sprintf("Agent shell bootstraps %s", agentEnvPath))

	if err := r.MkdirAll(hostWrapperDir(), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", hostWrapperDir(), err)
	}

	sandboxBin, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve sandbox binary path: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(sandboxBin); err == nil {
		sandboxBin = resolved
	}

	wrappers := []struct {
		name       string
		subcommand string
	}{
		{name: hostClaudeWrapperName, subcommand: "claude"},
		{name: hostExecWrapperName, subcommand: "exec"},
		{name: hostShellWrapperName, subcommand: "shell"},
	}
	for _, wrapper := range wrappers {
		path := hostWrapperPath(wrapper.name)
		if err := r.UserWriteFile(path, hostWrapperContent(sandboxBin, wrapper.subcommand)); err != nil {
			return fmt.Errorf("write wrapper %s: %w", path, err)
		}
		if err := r.Chmod(path, 0o755); err != nil {
			return fmt.Errorf("chmod %s: %w", path, err)
		}
		ui.Ok(fmt.Sprintf("Installed host wrapper %s", path))
	}

	userZshrc := userZshrcPath()
	userZshrcData, _ := os.ReadFile(userZshrc)
	if strings.Contains(string(userZshrcData), "/.local/bin") {
		ui.SkipDone(fmt.Sprintf("%s already configures ~/.local/bin in PATH", userZshrc))
		return nil
	}

	updatedUserZshrc := upsertManagedBlock(string(userZshrcData),
		userPathBlockStart,
		userPathBlockEnd,
		`export PATH="$HOME/.local/bin:$PATH"`,
	)
	if err := r.UserWriteFile(userZshrc, updatedUserZshrc); err != nil {
		return fmt.Errorf("update %s: %w", userZshrc, err)
	}
	ui.Ok(fmt.Sprintf("Added ~/.local/bin PATH block to %s", userZshrc))

	return nil
}

// ── Step 6: Passwordless sudo ─────────────────────────────────────────────────

func setupSudoers(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Configure passwordless sudo (%s → %s)", currentUser, agentUser))

	// sudoOutput is a read — bypasses Runner.
	if data, err := sudoOutput("cat", sudoersFile); err == nil &&
		strings.Contains(data, currentUser) {
		ui.SkipDone("Sudoers entry already exists")
	} else {
		entry := fmt.Sprintf("%s ALL=(%s) NOPASSWD: ALL\n", currentUser, agentUser)
		if err := r.SudoWriteFile(sudoersFile, entry); err != nil {
			return fmt.Errorf("write sudoers: %w", err)
		}
		if err := r.Sudo("chmod", "440", sudoersFile); err != nil {
			return fmt.Errorf("chmod sudoers: %w", err)
		}
		if err := r.Sudo("visudo", "-c", "-f", sudoersFile); err != nil {
			// Validation failed: clean up the invalid file and bail.
			// Direct sudo() here because this is error recovery, not
			// a primary operation — we never want to skip or preview it.
			sudo("rm", "-f", sudoersFile) //nolint:errcheck
			return fmt.Errorf("sudoers syntax invalid — entry removed. Configure manually: %w", err)
		}
		ui.Ok(fmt.Sprintf("Sudoers entry created: %s can switch to %s without password",
			currentUser, agentUser))
	}

	// Smoke-test that the sudo rule works. r.Sudo returns nil in dry-run,
	// which naturally prints the "verified" message — correct for a preview.
	if err := r.Sudo("-u", agentUser, "whoami"); err != nil {
		ui.WarnMsg(fmt.Sprintf("sudo -u %s failed — you may be prompted for a password", agentUser))
	} else {
		ui.Ok(fmt.Sprintf("Verified: sudo -u %s works", agentUser))
	}
	return nil
}

// ── Step 6: pf firewall ───────────────────────────────────────────────────────

func setupPfFirewall(ui *UI, r *Runner) error {
	ui.Step("Configure pf port blocklist")

	if _, err := os.Stat(pfAnchorFile); err == nil {
		ui.SkipDone(fmt.Sprintf("pf anchor file already exists at %s", pfAnchorFile))
		ui.WarnMsg(fmt.Sprintf("To replace it, delete first: sudo rm %s", pfAnchorFile))
	} else {
		if err := r.SudoWriteFile(pfAnchorFile, pfAnchorContent); err != nil {
			return fmt.Errorf("write pf anchor: %w", err)
		}
		ui.Ok(fmt.Sprintf("Created pf anchor at %s", pfAnchorFile))
	}

	// os.ReadFile is a read — bypasses Runner.
	pfConf, err := os.ReadFile("/etc/pf.conf")
	if err != nil {
		return fmt.Errorf("read /etc/pf.conf: %w", err)
	}
	if strings.Contains(string(pfConf), `anchor "agent"`) {
		ui.SkipDone("Anchor already registered in /etc/pf.conf")
	} else {
		ts := time.Now().Format("20060102150405")
		if err := r.Sudo("cp", "/etc/pf.conf", "/etc/pf.conf.backup."+ts); err != nil {
			return fmt.Errorf("backup pf.conf: %w", err)
		}
		ui.Ok("Backed up /etc/pf.conf")

		if err := r.SudoAppendFile("/etc/pf.conf", pfConfAddition); err != nil {
			return fmt.Errorf("append to pf.conf: %w", err)
		}
		ui.Ok("Registered anchor in /etc/pf.conf")
	}

	if err := r.PfctlLoad(); err != nil {
		ui.WarnMsg(fmt.Sprintf("pfctl failed to load rules: %v", err))
	} else {
		ui.Ok("pf rules loaded")
	}
	// pfctl -e returns 1 if already enabled — not an error, ignore it.
	r.Sudo("pfctl", "-e") //nolint:errcheck
	ui.Ok("pf enabled")
	return nil
}

// ── Step 7: DNS blocklist ─────────────────────────────────────────────────────

func setupDNSBlocklist(ui *UI, r *Runner) error {
	ui.Step("Configure DNS domain blocklist")

	// os.ReadFile is a read — bypasses Runner.
	hosts, err := os.ReadFile("/etc/hosts")
	if err != nil {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	if strings.Contains(string(hosts), hostsMarker) {
		ui.SkipDone("DNS blocklist already present in /etc/hosts")
		ui.WarnMsg(fmt.Sprintf("To replace it, remove the block between '%s' markers first.", hostsMarker))
		return nil
	}

	if !ui.Ask("Add DNS blocklist to /etc/hosts? (blocks tunnel/paste/fileshare domains system-wide)") {
		ui.WarnMsg("Skipped DNS blocklist. See soft-pf-blocklist.md for alternatives (dnsmasq, NextDNS).")
		return nil
	}

	if err := r.SudoAppendFile("/etc/hosts", hostsBlocklistContent); err != nil {
		return fmt.Errorf("append to /etc/hosts: %w", err)
	}

	// Cache flush is fire-and-forget; ignore errors.
	r.Sudo("dscacheutil", "-flushcache")       //nolint:errcheck
	r.Sudo("killall", "-HUP", "mDNSResponder") //nolint:errcheck
	ui.Ok("DNS blocklist added to /etc/hosts and cache flushed")
	ui.WarnMsg("This is system-wide. /etc/hosts does not block subdomains.")
	ui.WarnMsg("For wildcard blocking (*.ngrok.io), use dnsmasq — see soft-pf-blocklist.md")
	return nil
}

// ── Step 8: LaunchDaemon ──────────────────────────────────────────────────────

func setupLaunchDaemon(ui *UI, r *Runner) error {
	ui.Step("Persist firewall across reboots")

	if _, err := os.Stat(pfDaemonPlist); err == nil {
		ui.SkipDone(fmt.Sprintf("LaunchDaemon already exists at %s", pfDaemonPlist))
		return nil
	}

	if err := r.SudoWriteFile(pfDaemonPlist, pfDaemonPlistContent); err != nil {
		return fmt.Errorf("write LaunchDaemon plist: %w", err)
	}
	if err := r.Sudo("chmod", "644", pfDaemonPlist); err != nil {
		return fmt.Errorf("chmod plist: %w", err)
	}
	if err := r.LaunchctlBootstrap(pfDaemonPlist); err != nil {
		ui.WarnMsg(fmt.Sprintf("launchctl bootstrap: %v — plist written but not loaded", err))
	} else {
		ui.Ok("LaunchDaemon installed — pf rules will reload on boot")
	}
	return nil
}

// ── Verify ────────────────────────────────────────────────────────────────────

// verifySetup re-checks key invariants after all steps complete.
// All operations here are read-only; no Runner needed.
// Uses TestPass/TestFail/TestWarn so callers (sandbox status) can check
// ui.Fail > 0 and return a non-zero exit code when the sandbox is broken.
func verifySetup(ui *UI) {
	ui.Step("Verify setup")
	fmt.Println()

	if u, err := user.Lookup(agentUser); err == nil {
		ui.TestPass(fmt.Sprintf("User '%s' exists (uid=%s)", agentUser, u.Uid))
	} else {
		ui.TestFail(fmt.Sprintf("User '%s' not found", agentUser))
	}

	if _, err := os.Stat(agentHome); err == nil {
		ui.TestPass(fmt.Sprintf("Home directory exists at %s", agentHome))
	} else {
		ui.TestFail(fmt.Sprintf("Home directory missing: %s", agentHome))
	}

	if info, err := os.Stat(sharedWorkspace); err == nil {
		ui.TestPass(fmt.Sprintf("Workspace root exists at %s (%s)", sharedWorkspace, info.Mode()))
	} else {
		ui.TestFail(fmt.Sprintf("Workspace root missing: %s", sharedWorkspace))
	}

	if homeAllowsAgentTraverse(os.Getenv("HOME")) {
		if homeHasAgentTraverseACL(os.Getenv("HOME")) {
			ui.TestPass(fmt.Sprintf("Home directory ACL lets '%s' traverse to %s", agentUser, workspaceHint))
		} else {
			ui.TestPass(fmt.Sprintf("Home directory permissions already let '%s' reach %s", agentUser, workspaceHint))
		}
	} else {
		ui.TestWarn(fmt.Sprintf("Home directory access for '%s' not detected — %s may be inaccessible from the sandbox", agentUser, workspaceHint))
	}

	// ACL is advisory: files are still accessible via the dev group,
	// but new files created with umask 077 need the ACL to be readable.
	if workspaceHasDevACL() {
		ui.TestPass(fmt.Sprintf("Workspace ACL grants '%s' group inherited read/write access", sharedGroup))
	} else {
		ui.TestWarn(fmt.Sprintf("Workspace ACL missing '%s' group — agent files may not be readable by controlling user", sharedGroup))
	}

	if out, err := sudoOutput("pfctl", "-a", pfAnchorName, "-sr"); err == nil &&
		strings.Contains(out, "block") {
		n := len(strings.Split(strings.TrimSpace(out), "\n"))
		ui.TestPass(fmt.Sprintf("pf anchor loaded with %d rules", n))
	} else {
		ui.TestFail("pf anchor not loaded or empty — try: sudo pfctl -f /etc/pf.conf && sudo pfctl -e")
	}

	if out, err := sudoOutput("pfctl", "-si"); err == nil &&
		strings.Contains(out, "Status: Enabled") {
		ui.TestPass("pf is enabled")
	} else {
		ui.TestFail("pf is not enabled — run: sudo pfctl -e")
	}

	if err := sudo("-u", agentUser, "whoami"); err == nil {
		ui.TestPass(fmt.Sprintf("Passwordless sudo works (%s → %s)", os.Getenv("USER"), agentUser))
	} else {
		ui.TestFail("Passwordless sudo not working")
	}

	// DNS blocklist is optional — was a prompted step during setup.
	if data, err := os.ReadFile("/etc/hosts"); err == nil &&
		strings.Contains(string(data), "AI Agent Blocklist") {
		n := strings.Count(string(data), "0.0.0.0 ")
		ui.TestPass(fmt.Sprintf("DNS blocklist active (%d domains in /etc/hosts)", n))
	} else {
		ui.TestWarn("DNS blocklist not installed in /etc/hosts (optional — see setup-option-a.md)")
	}

	if _, err := os.Stat(seatbeltProfilePath); err == nil {
		ui.TestPass(fmt.Sprintf("Seatbelt profile installed at %s", seatbeltProfilePath))
	} else {
		ui.TestFail(fmt.Sprintf("Seatbelt profile missing: %s", seatbeltProfilePath))
	}

	if info, err := os.Stat(seatbeltWrapperPath); err == nil && info.Mode()&0o111 != 0 {
		ui.TestPass(fmt.Sprintf("Seatbelt wrapper installed and executable at %s", seatbeltWrapperPath))
	} else {
		ui.TestFail(fmt.Sprintf("Seatbelt wrapper missing or not executable: %s", seatbeltWrapperPath))
	}

	// Agent shell env is advisory — wrappers work without it but PATH and
	// aliases inside agent-shell will be incomplete.
	if _, err := os.Stat(agentEnvPath); err == nil {
		ui.TestPass(fmt.Sprintf("Agent shell env installed at %s", agentEnvPath))
	} else {
		ui.TestWarn(fmt.Sprintf("Agent shell env missing: %s", agentEnvPath))
	}

	for _, wrapper := range []string{hostClaudeWrapperName, hostExecWrapperName, hostShellWrapperName} {
		path := hostWrapperPath(wrapper)
		if info, err := os.Stat(path); err == nil && info.Mode()&0o111 != 0 {
			ui.TestPass(fmt.Sprintf("Host wrapper installed: %s", path))
		} else {
			ui.TestFail(fmt.Sprintf("Host wrapper missing or not executable: %s", path))
		}
	}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func checkPlatform() error {
	cmd := exec.Command("uname")
	out, err := cmd.Output()
	if err != nil || strings.TrimSpace(string(out)) != "Darwin" {
		return fmt.Errorf("this tool is for macOS only")
	}
	return nil
}

func uidTaken(uid string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-list", "/Users", "UniqueID")
	if err != nil {
		return false, fmt.Errorf("dscl list UIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == uid {
			return true, nil
		}
	}
	return false, nil
}

func gidTaken(gid string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-list", "/Groups", "PrimaryGroupID")
	if err != nil {
		return false, fmt.Errorf("dscl list GIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == gid {
			return true, nil
		}
	}
	return false, nil
}

// workspaceHasDevACL returns true when the workspace directory already has an
// inherited ACE for the shared group, so the setup step can be skipped.
func workspaceHasDevACL() bool {
	out, err := exec.Command("ls", "-led", sharedWorkspace).CombinedOutput()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "group:"+sharedGroup)
}

func homeTraverseACLEntry() string {
	return "user:" + agentUser + " allow execute,readattr,readextattr,readsecurity"
}

func homeHasAgentTraverseACL(homeDir string) bool {
	out, err := exec.Command("ls", "-led", homeDir).CombinedOutput()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "user:"+agentUser) &&
		strings.Contains(string(out), " allow execute")
}

func homeAllowsAgentTraverse(homeDir string) bool {
	if homeHasAgentTraverseACL(homeDir) {
		return true
	}

	info, err := os.Stat(homeDir)
	if err != nil {
		return false
	}
	if info.Mode().Perm()&0o001 != 0 {
		return true
	}
	if info.Mode().Perm()&0o010 == 0 {
		return false
	}

	st, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return false
	}
	group, err := user.LookupGroupId(fmt.Sprintf("%d", st.Gid))
	if err != nil {
		return false
	}
	member, err := groupMembershipContains(group.Name, agentUser)
	if err != nil {
		return false
	}
	return member
}

func groupMembershipContains(group, username string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-read", "/Groups/"+group, "GroupMembership")
	if err != nil {
		return false, nil // group exists but has no members yet
	}
	for _, field := range strings.Fields(out) {
		if field == username {
			return true, nil
		}
	}
	return false, nil
}
