package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

// ── Embedded content ──────────────────────────────────────────────────────────

const pfAnchorContent = `# =============================================================
# Soft blocklist for the "agent" user
# Block known-bad ports/protocols; allow everything else
# Generated by sandbox setup
# =============================================================

# --- Block exfiltration / C2 protocols ---

# SMTP (email exfiltration)
block return out quick proto tcp from any to any port { 25, 465, 587 } user agent

# IRC (C2 channel)
block return out quick proto tcp from any to any port { 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6697 } user agent

# FTP (legacy file transfer)
block return out quick proto tcp from any to any port { 20, 21 } user agent

# Telnet (insecure remote access)
block return out quick proto tcp from any to any port 23 user agent

# SMB (lateral movement)
block return out quick proto tcp from any to any port 445 user agent

# RDP (remote desktop)
block return out quick proto tcp from any to any port 3389 user agent

# VNC (remote desktop)
block return out quick proto tcp from any to any port { 5900, 5901 } user agent

# Tor (anonymous exfiltration)
block return out quick proto tcp from any to any port { 9050, 9150 } user agent

# SOCKS proxy
block return out quick proto tcp from any to any port 1080 user agent

# VPN protocols
block return out quick proto tcp from any to any port { 1194, 1723 } user agent
block return out quick proto udp from any to any port { 1194, 1723, 4500 } user agent

# XMPP (messaging / C2)
block return out quick proto tcp from any to any port { 5222, 5269 } user agent

# --- Block ICMP tunneling ---
block return out quick proto icmp from any to any user agent

# --- Allow everything else ---
pass out quick user agent
`

const pfDaemonPlistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.local.pf-agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>/sbin/pfctl</string>
        <string>-f</string>
        <string>/etc/pf.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/pf-agent.log</string>
</dict>
</plist>
`

// pfConfAddition is appended to /etc/pf.conf to register the anchor.
// Leading newline provides a blank-line separator from existing content.
const pfConfAddition = `
# Claude Code sandbox user blocklist
anchor "agent"
load anchor "agent" from "/etc/pf.anchors/agent"
`

const hostsBlocklistContent = `
# === AI Agent Blocklist ===
# Tunnel services
0.0.0.0 ngrok.io
0.0.0.0 ngrok.com
0.0.0.0 ngrok-free.app
0.0.0.0 tunnel.cloudflare.com
0.0.0.0 trycloudflare.com
0.0.0.0 serveo.net
0.0.0.0 localtunnel.me
0.0.0.0 localhost.run
0.0.0.0 localxpose.io
0.0.0.0 pagekite.me
0.0.0.0 bore.digital
0.0.0.0 localtonet.com
0.0.0.0 zrok.io
0.0.0.0 devtunnels.ms
0.0.0.0 loca.lt
0.0.0.0 tunnelmole.com
0.0.0.0 playit.gg
0.0.0.0 pinggy.io
0.0.0.0 lokal.so
0.0.0.0 telebit.cloud
0.0.0.0 loophole.cloud
# Paste services
0.0.0.0 pastebin.com
0.0.0.0 paste.ee
0.0.0.0 ghostbin.com
0.0.0.0 hastebin.com
0.0.0.0 dpaste.org
0.0.0.0 justpaste.it
0.0.0.0 rentry.co
0.0.0.0 ix.io
# File sharing
0.0.0.0 transfer.sh
0.0.0.0 file.io
0.0.0.0 gofile.io
0.0.0.0 catbox.moe
0.0.0.0 filebin.net
# Webhook capture
0.0.0.0 webhook.site
0.0.0.0 requestbin.com
0.0.0.0 pipedream.com
0.0.0.0 hookbin.com
0.0.0.0 beeceptor.com
# === End AI Agent Blocklist ===
`

// ── Command ───────────────────────────────────────────────────────────────────

func newSetupCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "setup",
		Short: "Configure the macOS sandbox (Option A: dedicated agent user + pf firewall)",
		RunE:  runSetup,
	}
}

// runSetup is the top-level entry point.  Named return so defer can inspect
// retErr and print the rollback hint — equivalent to shell's "trap ... ERR".
func runSetup(_ *cobra.Command, _ []string) (retErr error) {
	ui := &UI{DryRun: flagDryRun}
	r := NewRunner(ui, flagVerbose, flagDryRun)

	if err := checkPlatform(); err != nil {
		ui.Fatal(err.Error())
	}

	cu, err := user.Current()
	if err != nil {
		return fmt.Errorf("cannot determine current user: %w", err)
	}
	if cu.Username == "root" {
		ui.Fatal("Run as your normal user, not root. The tool uses sudo where needed.")
	}

	ui.Banner(cu.Username)

	if flagDryRun {
		cYellow.Println("  ────────────────────────────────────────────────────")
		cYellow.Println("  DRY RUN — no changes will be made.")
		cYellow.Println("  Shows all commands regardless of current system state.")
		cYellow.Println("  Steps already complete are skipped when run for real.")
		cYellow.Println("  ────────────────────────────────────────────────────")
		fmt.Println()
	} else if !ui.Ask("Proceed with setup?") {
		fmt.Println("  Aborted.")
		return nil
	}

	defer func() {
		if retErr != nil && !flagDryRun {
			fmt.Fprintln(os.Stderr)
			cRed.Fprintln(os.Stderr, "Setup interrupted — some steps may be incomplete.")
			fmt.Fprintln(os.Stderr, "See setup-option-a.md § Uninstall / Rollback")
		}
	}()

	if err := setupAgentUser(ui, r); err != nil {
		return err
	}
	if err := setupDevGroup(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupSharedWorkspace(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupHardeningGaps(ui, r); err != nil {
		return err
	}
	if err := setupSudoers(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupPfFirewall(ui, r); err != nil {
		return err
	}
	if err := setupDNSBlocklist(ui, r); err != nil {
		return err
	}
	if err := setupLaunchDaemon(ui, r); err != nil {
		return err
	}

	verifySetup(ui)

	if !flagDryRun {
		ui.DoneBox(cu.Username)
	}
	return nil
}

// ── Step 1: Agent user ────────────────────────────────────────────────────────

func setupAgentUser(ui *UI, r *Runner) error {
	ui.Step(fmt.Sprintf("Create '%s' user", agentUser))

	if u, err := user.Lookup(agentUser); err == nil {
		ui.SkipDone(fmt.Sprintf("User '%s' already exists (uid=%s)", agentUser, u.Uid))
		return nil
	}

	if taken, err := uidTaken(agentUID); err != nil {
		return fmt.Errorf("check UID: %w", err)
	} else if taken {
		return fmt.Errorf("UID %s is already taken — edit agentUID in main.go", agentUID)
	}

	record := "/Users/" + agentUser
	for _, args := range [][]string{
		{"dscl", ".", "-create", record},
		{"dscl", ".", "-create", record, "UserShell", "/bin/zsh"},
		{"dscl", ".", "-create", record, "UniqueID", agentUID},
		{"dscl", ".", "-create", record, "PrimaryGroupID", "20"},
		{"dscl", ".", "-create", record, "NFSHomeDirectory", agentHome},
	} {
		if err := r.Sudo(args...); err != nil {
			return fmt.Errorf("dscl %v: %w", args[2:], err)
		}
	}
	ui.Ok("User record created")

	if err := r.Sudo("mkdir", "-p", agentHome); err != nil {
		return fmt.Errorf("mkdir %s: %w", agentHome, err)
	}
	if err := r.Sudo("chown", agentUser+":staff", agentHome); err != nil {
		return fmt.Errorf("chown %s: %w", agentHome, err)
	}
	// createhomedir may exit non-zero even on success; ignore the error.
	r.Sudo("createhomedir", "-c", "-u", agentUser) //nolint:errcheck
	ui.Ok(fmt.Sprintf("Home directory created at %s", agentHome))

	if err := r.Sudo("dscl", ".", "-create", record, "IsHidden", "1"); err != nil {
		return fmt.Errorf("hide user: %w", err)
	}
	ui.Ok("Hidden from login screen")

	fmt.Printf("\n  Set a password for the '%s' user:\n", agentUser)
	if err := r.Interactive("sudo", "passwd", agentUser); err != nil {
		return fmt.Errorf("passwd: %w", err)
	}
	ui.Ok("Password set")

	if _, err := user.Lookup(agentUser); err != nil {
		return fmt.Errorf("user '%s' not found after creation: %w", agentUser, err)
	}
	return nil
}

// ── Step 2: Dev group ─────────────────────────────────────────────────────────

func setupDevGroup(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Create '%s' group", sharedGroup))

	if g, err := user.LookupGroup(sharedGroup); err == nil {
		ui.SkipDone(fmt.Sprintf("Group '%s' already exists (gid=%s)", sharedGroup, g.Gid))
	} else {
		if taken, err := gidTaken(sharedGID); err != nil {
			return fmt.Errorf("check GID: %w", err)
		} else if taken {
			return fmt.Errorf("GID %s is already taken — edit sharedGID in main.go", sharedGID)
		}

		record := "/Groups/" + sharedGroup
		for _, args := range [][]string{
			{"dscl", ".", "-create", record},
			{"dscl", ".", "-create", record, "PrimaryGroupID", sharedGID},
			{"dscl", ".", "-create", record, "RealName", "Shared dev workspace"},
		} {
			if err := r.Sudo(args...); err != nil {
				return fmt.Errorf("dscl %v: %w", args[2:], err)
			}
		}
		ui.Ok(fmt.Sprintf("Group '%s' created (gid=%s)", sharedGroup, sharedGID))
	}

	for _, u := range []string{currentUser, agentUser} {
		member, err := groupMembershipContains(sharedGroup, u)
		if err != nil {
			return err
		}
		if member {
			ui.SkipDone(fmt.Sprintf("%s is already a member of '%s'", u, sharedGroup))
		} else {
			if err := r.Sudo("dscl", ".", "-append",
				"/Groups/"+sharedGroup, "GroupMembership", u); err != nil {
				return fmt.Errorf("add %s to %s: %w", u, sharedGroup, err)
			}
			ui.Ok(fmt.Sprintf("Added %s to '%s'", u, sharedGroup))
		}
	}
	return nil
}

// ── Step 3: Shared workspace ──────────────────────────────────────────────────

func setupSharedWorkspace(ui *UI, r *Runner, currentUser string) error {
	ui.Step("Set up shared workspace")

	if _, err := os.Stat(sharedWorkspace); os.IsNotExist(err) {
		if err := r.Sudo("mkdir", "-p", sharedWorkspace); err != nil {
			return fmt.Errorf("mkdir %s: %w", sharedWorkspace, err)
		}
		ui.Ok(fmt.Sprintf("Created %s", sharedWorkspace))
	} else {
		ui.SkipDone(fmt.Sprintf("Shared workspace exists at %s", sharedWorkspace))
	}

	if err := r.Sudo("chown", currentUser+":"+sharedGroup, sharedWorkspace); err != nil {
		return fmt.Errorf("chown %s: %w", sharedWorkspace, err)
	}
	if err := r.Sudo("chmod", "770", sharedWorkspace); err != nil {
		return fmt.Errorf("chmod 770 %s: %w", sharedWorkspace, err)
	}
	if err := r.Sudo("chmod", "g+s", sharedWorkspace); err != nil {
		return fmt.Errorf("chmod g+s %s: %w", sharedWorkspace, err)
	}
	ui.Ok(fmt.Sprintf("Permissions: 770, setgid, owner %s:%s", currentUser, sharedGroup))

	// Symlink from current user's home
	symlink := os.Getenv("HOME") + "/workspace-shared"
	if info, err := os.Lstat(symlink); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			ui.SkipDone("Symlink ~/workspace-shared already exists")
		} else {
			ui.WarnMsg("~/workspace-shared exists but is not a symlink — skipping")
		}
	} else {
		if err := r.Symlink(sharedWorkspace, symlink); err != nil {
			return fmt.Errorf("symlink ~/workspace-shared: %w", err)
		}
		ui.Ok(fmt.Sprintf("Created symlink ~/workspace-shared → %s", sharedWorkspace))
	}

	// Symlink from agent user's home
	// asAgentQuiet("test", ...) is a read-only check — bypasses Runner.
	agentLink := agentHome + "/workspace"
	if asAgentQuiet("test", "-L", agentLink) == nil {
		ui.SkipDone(fmt.Sprintf("Symlink %s already exists", agentLink))
	} else if asAgentQuiet("test", "-e", agentLink) == nil {
		ui.WarnMsg(fmt.Sprintf("%s exists but is not a symlink — skipping", agentLink))
	} else {
		if err := r.AsAgent("ln", "-s", sharedWorkspace, agentLink); err != nil {
			return fmt.Errorf("symlink %s: %w", agentLink, err)
		}
		ui.Ok(fmt.Sprintf("Created symlink %s → %s", agentLink, sharedWorkspace))
	}
	return nil
}

// ── Step 4: Hardening gaps ────────────────────────────────────────────────────

func setupHardeningGaps(ui *UI, r *Runner) error {
	ui.Step("Harden known macOS isolation gaps")

	// Docker socket — owned by current user, no sudo needed.
	dockerSock := os.Getenv("HOME") + "/.docker/run/docker.sock"
	if info, err := os.Stat(dockerSock); err == nil && info.Mode()&os.ModeSocket != 0 {
		current := info.Mode().Perm()
		if current == 0o700 {
			ui.SkipDone("Docker socket already restricted (700)")
		} else {
			if err := r.Chmod(dockerSock, 0o700); err != nil {
				return fmt.Errorf("chmod docker socket: %w", err)
			}
			ui.Ok(fmt.Sprintf("Docker socket restricted to owner only (was %04o)", current))
		}
	} else {
		ui.SkipDone("Docker socket not found (Docker Desktop not running or not installed)")
	}

	// Restrictive umask for agent user.
	// asAgentOutput is a read — bypasses Runner.
	agentZshrc := agentHome + "/.zshrc"
	if out, _ := asAgentOutput("cat", agentZshrc); strings.Contains(out, "umask 077") {
		ui.SkipDone("umask 077 already set in agent's .zshrc")
	} else {
		if err := r.SudoAppendFile(agentZshrc, "umask 077\n"); err != nil {
			return fmt.Errorf("set umask in agent .zshrc: %w", err)
		}
		ui.Ok("Set umask 077 in agent's .zshrc")
	}

	// Restrictive umask for current user.
	// os.ReadFile is a read — bypasses Runner.
	userZshrc := os.Getenv("HOME") + "/.zshrc"
	if data, err := os.ReadFile(userZshrc); err == nil && strings.Contains(string(data), "umask 077") {
		ui.SkipDone("umask 077 already set in your .zshrc")
	} else if ui.Ask("Add 'umask 077' to your .zshrc? (prevents /tmp leakage)") {
		if err := r.UserAppendFile(userZshrc, "umask 077\n"); err != nil {
			return fmt.Errorf("write .zshrc: %w", err)
		}
		ui.Ok("Set umask 077 in your .zshrc")
	} else {
		ui.WarnMsg("Skipped. Consider adding 'umask 077' manually.")
	}

	return nil
}

// ── Step 5: Passwordless sudo ─────────────────────────────────────────────────

func setupSudoers(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Configure passwordless sudo (%s → %s)", currentUser, agentUser))

	// sudoOutput is a read — bypasses Runner.
	if data, err := sudoOutput("cat", sudoersFile); err == nil &&
		strings.Contains(data, currentUser) {
		ui.SkipDone("Sudoers entry already exists")
	} else {
		entry := fmt.Sprintf("%s ALL=(%s) NOPASSWD: ALL\n", currentUser, agentUser)
		if err := r.SudoWriteFile(sudoersFile, entry); err != nil {
			return fmt.Errorf("write sudoers: %w", err)
		}
		if err := r.Sudo("chmod", "440", sudoersFile); err != nil {
			return fmt.Errorf("chmod sudoers: %w", err)
		}
		if err := r.Sudo("visudo", "-c", "-f", sudoersFile); err != nil {
			// Validation failed: clean up the invalid file and bail.
			// Direct sudo() here because this is error recovery, not
			// a primary operation — we never want to skip or preview it.
			sudo("rm", "-f", sudoersFile) //nolint:errcheck
			return fmt.Errorf("sudoers syntax invalid — entry removed. Configure manually: %w", err)
		}
		ui.Ok(fmt.Sprintf("Sudoers entry created: %s can switch to %s without password",
			currentUser, agentUser))
	}

	// Smoke-test that the sudo rule works. r.Sudo returns nil in dry-run,
	// which naturally prints the "verified" message — correct for a preview.
	if err := r.Sudo("-u", agentUser, "whoami"); err != nil {
		ui.WarnMsg(fmt.Sprintf("sudo -u %s failed — you may be prompted for a password", agentUser))
	} else {
		ui.Ok(fmt.Sprintf("Verified: sudo -u %s works", agentUser))
	}
	return nil
}

// ── Step 6: pf firewall ───────────────────────────────────────────────────────

func setupPfFirewall(ui *UI, r *Runner) error {
	ui.Step("Configure pf port blocklist")

	if _, err := os.Stat(pfAnchorFile); err == nil {
		ui.SkipDone(fmt.Sprintf("pf anchor file already exists at %s", pfAnchorFile))
		ui.WarnMsg(fmt.Sprintf("To replace it, delete first: sudo rm %s", pfAnchorFile))
	} else {
		if err := r.SudoWriteFile(pfAnchorFile, pfAnchorContent); err != nil {
			return fmt.Errorf("write pf anchor: %w", err)
		}
		ui.Ok(fmt.Sprintf("Created pf anchor at %s", pfAnchorFile))
	}

	// os.ReadFile is a read — bypasses Runner.
	pfConf, err := os.ReadFile("/etc/pf.conf")
	if err != nil {
		return fmt.Errorf("read /etc/pf.conf: %w", err)
	}
	if strings.Contains(string(pfConf), `anchor "agent"`) {
		ui.SkipDone("Anchor already registered in /etc/pf.conf")
	} else {
		ts := time.Now().Format("20060102150405")
		if err := r.Sudo("cp", "/etc/pf.conf", "/etc/pf.conf.backup."+ts); err != nil {
			return fmt.Errorf("backup pf.conf: %w", err)
		}
		ui.Ok("Backed up /etc/pf.conf")

		if err := r.SudoAppendFile("/etc/pf.conf", pfConfAddition); err != nil {
			return fmt.Errorf("append to pf.conf: %w", err)
		}
		ui.Ok("Registered anchor in /etc/pf.conf")
	}

	if err := r.PfctlLoad(); err != nil {
		ui.WarnMsg(fmt.Sprintf("pfctl failed to load rules: %v", err))
	} else {
		ui.Ok("pf rules loaded")
	}
	// pfctl -e returns 1 if already enabled — not an error, ignore it.
	r.Sudo("pfctl", "-e") //nolint:errcheck
	ui.Ok("pf enabled")
	return nil
}

// ── Step 7: DNS blocklist ─────────────────────────────────────────────────────

func setupDNSBlocklist(ui *UI, r *Runner) error {
	ui.Step("Configure DNS domain blocklist")

	// os.ReadFile is a read — bypasses Runner.
	hosts, err := os.ReadFile("/etc/hosts")
	if err != nil {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	if strings.Contains(string(hosts), hostsMarker) {
		ui.SkipDone("DNS blocklist already present in /etc/hosts")
		ui.WarnMsg(fmt.Sprintf("To replace it, remove the block between '%s' markers first.", hostsMarker))
		return nil
	}

	if !ui.Ask("Add DNS blocklist to /etc/hosts? (blocks tunnel/paste/fileshare domains system-wide)") {
		ui.WarnMsg("Skipped DNS blocklist. See soft-pf-blocklist.md for alternatives (dnsmasq, NextDNS).")
		return nil
	}

	if err := r.SudoAppendFile("/etc/hosts", hostsBlocklistContent); err != nil {
		return fmt.Errorf("append to /etc/hosts: %w", err)
	}

	// Cache flush is fire-and-forget; ignore errors.
	r.Sudo("dscacheutil", "-flushcache")       //nolint:errcheck
	r.Sudo("killall", "-HUP", "mDNSResponder") //nolint:errcheck
	ui.Ok("DNS blocklist added to /etc/hosts and cache flushed")
	ui.WarnMsg("This is system-wide. /etc/hosts does not block subdomains.")
	ui.WarnMsg("For wildcard blocking (*.ngrok.io), use dnsmasq — see soft-pf-blocklist.md")
	return nil
}

// ── Step 8: LaunchDaemon ──────────────────────────────────────────────────────

func setupLaunchDaemon(ui *UI, r *Runner) error {
	ui.Step("Persist firewall across reboots")

	if _, err := os.Stat(pfDaemonPlist); err == nil {
		ui.SkipDone(fmt.Sprintf("LaunchDaemon already exists at %s", pfDaemonPlist))
		return nil
	}

	if err := r.SudoWriteFile(pfDaemonPlist, pfDaemonPlistContent); err != nil {
		return fmt.Errorf("write LaunchDaemon plist: %w", err)
	}
	if err := r.Sudo("chmod", "644", pfDaemonPlist); err != nil {
		return fmt.Errorf("chmod plist: %w", err)
	}
	if err := r.LaunchctlBootstrap(pfDaemonPlist); err != nil {
		ui.WarnMsg(fmt.Sprintf("launchctl bootstrap: %v — plist written but not loaded", err))
	} else {
		ui.Ok("LaunchDaemon installed — pf rules will reload on boot")
	}
	return nil
}

// ── Verify ────────────────────────────────────────────────────────────────────

// verifySetup re-checks key invariants after all steps complete.
// All operations here are read-only; no Runner needed.
func verifySetup(ui *UI) {
	ui.Step("Verify setup")
	fmt.Println()

	if u, err := user.Lookup(agentUser); err == nil {
		ui.Ok(fmt.Sprintf("User '%s' exists (uid=%s)", agentUser, u.Uid))
	} else {
		ui.WarnMsg(fmt.Sprintf("User '%s' not found", agentUser))
	}

	if _, err := os.Stat(agentHome); err == nil {
		ui.Ok(fmt.Sprintf("Home directory exists at %s", agentHome))
	} else {
		ui.WarnMsg(fmt.Sprintf("Home directory missing: %s", agentHome))
	}

	if info, err := os.Stat(sharedWorkspace); err == nil {
		ui.Ok(fmt.Sprintf("Shared workspace exists at %s (%s)", sharedWorkspace, info.Mode()))
	} else {
		ui.WarnMsg(fmt.Sprintf("Shared workspace missing: %s", sharedWorkspace))
	}

	if out, err := sudoOutput("pfctl", "-a", pfAnchorName, "-sr"); err == nil &&
		strings.Contains(out, "block") {
		n := len(strings.Split(strings.TrimSpace(out), "\n"))
		ui.Ok(fmt.Sprintf("pf anchor loaded with %d rules", n))
	} else {
		ui.WarnMsg("pf anchor not loaded or empty — try: sudo pfctl -f /etc/pf.conf && sudo pfctl -e")
	}

	if out, err := sudoOutput("pfctl", "-si"); err == nil &&
		strings.Contains(out, "Status: Enabled") {
		ui.Ok("pf is enabled")
	} else {
		ui.WarnMsg("pf is not enabled — run: sudo pfctl -e")
	}

	if err := sudo("-u", agentUser, "whoami"); err == nil {
		ui.Ok(fmt.Sprintf("Passwordless sudo works (%s → %s)", os.Getenv("USER"), agentUser))
	} else {
		ui.WarnMsg("Passwordless sudo not working")
	}

	if data, err := os.ReadFile("/etc/hosts"); err == nil &&
		strings.Contains(string(data), "AI Agent Blocklist") {
		n := strings.Count(string(data), "0.0.0.0 ")
		ui.Ok(fmt.Sprintf("DNS blocklist active (%d domains in /etc/hosts)", n))
	} else {
		ui.WarnMsg("DNS blocklist not installed in /etc/hosts")
	}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func checkPlatform() error {
	cmd := exec.Command("uname")
	out, err := cmd.Output()
	if err != nil || strings.TrimSpace(string(out)) != "Darwin" {
		return fmt.Errorf("this tool is for macOS only")
	}
	return nil
}

func uidTaken(uid string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-list", "/Users", "UniqueID")
	if err != nil {
		return false, fmt.Errorf("dscl list UIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == uid {
			return true, nil
		}
	}
	return false, nil
}

func gidTaken(gid string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-list", "/Groups", "PrimaryGroupID")
	if err != nil {
		return false, fmt.Errorf("dscl list GIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == gid {
			return true, nil
		}
	}
	return false, nil
}

func groupMembershipContains(group, username string) (bool, error) {
	out, err := sudoOutput("dscl", ".", "-read", "/Groups/"+group, "GroupMembership")
	if err != nil {
		return false, nil // group exists but has no members yet
	}
	for _, field := range strings.Fields(out) {
		if field == username {
			return true, nil
		}
	}
	return false, nil
}
