// hazmat-launch is the narrow privileged helper that bridges the dr→agent
// privilege gap for Hazmat-owned agent operations.
//
// It is the sole binary covered by the NOPASSWD sudoers rule:
//
//	dr ALL = (agent) NOPASSWD: /usr/local/libexec/hazmat-launch
//	dr ALL = (agent) NOPASSWD: sha256:<digest> /Users/dr/.local/libexec/hazmat-launch
//
// Unlike granting NOPASSWD to /usr/bin/sandbox-exec directly, this helper:
//   - Accepts only a policy file path (no inline policies)
//   - Validates the policy file is at /private/tmp/hazmat-<pid>.sb
//   - Validates the policy file is owned by the invoking user (SUDO_UID),
//     not by root or agent, to prevent pre-planted policy substitution
//   - Validates the policy file has mode 0644
//   - Validates the policy contains (deny default)
//
// Instead of exec'ing sandbox-exec, this helper calls sandbox_init()
// directly via cgo and then execs the target command. This eliminates
// the sandbox-exec process from the chain, giving:
//   - Correct signal forwarding (the process IS the target)
//   - Proper PTY handling for interactive TUI applications
//   - One fewer process in the sudo → sandbox → target chain
//
// Intentional use of deprecated API: sandbox_init() and sandbox_free_error()
// have been deprecated since macOS 10.8. There is no public, non-deprecated
// replacement for applying an SBPL policy string to the current process at
// runtime. Apple's recommended replacement is App Sandbox (entitlements
// declared at build time), which cannot generate per-session policies.
// The private alternatives (sandbox_compile_string, sandbox_apply) are absent
// from all public SDK headers and are worse to depend on. sandbox-exec(1) is
// also deprecated and wraps the same functions. If Apple removes sandbox_init,
// the build will fail with a link error and we will have to revert to exec'ing
// sandbox-exec, losing correct signal forwarding and PTY handling.
//
// Usage:
//
//	sudo -u agent <hazmat-launch> <policy-file> <cmd> [args...]
//	sudo -u agent <hazmat-launch> exec <cmd> [args...]

package main

/*
#cgo CFLAGS: -Wno-deprecated-declarations
#include <sandbox.h>
#include <stdlib.h>
*/
import "C"

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"regexp"
	"strconv"
	"syscall"
	"unsafe"

	"golang.org/x/sys/unix"
)

// policyFilePattern enforces that the policy file lives under /private/tmp
// and follows the hazmat-<pid>.sb naming convention.  The numeric PID
// component prevents traversal attacks (/private/tmp/../../etc/...).
var policyFilePattern = regexp.MustCompile(`^/private/tmp/hazmat-\d+\.sb$`)

// denyDefaultMarker is the literal string that every legitimate session policy
// generated by hazmat's generateSBPL starts with.  Policies that lack it
// (e.g. hand-written "(version 1)(allow default)" files) are rejected.
const denyDefaultMarker = "(deny default)"

func main() {
	if err := closeInheritedFDs(); err != nil {
		die("hazmat-launch: close inherited fds: %v", err)
	}

	if len(os.Args) < 2 {
		dieUsage()
	}

	if os.Args[1] == "exec" {
		if len(os.Args) < 3 {
			dieUsage()
		}
		execCommand(os.Args[2:])
		return
	}

	if len(os.Args) < 3 {
		dieUsage()
	}

	runLaunchMode(os.Args[1], os.Args[2:])
}

func runLaunchMode(policyFile string, cmdArgs []string) {
	policy, err := validateAndReadPolicy(policyFile)
	if err != nil {
		die("hazmat-launch: %v", err)
	}

	// Apply the seatbelt sandbox to this process. After sandbox_init(),
	// the sandbox is active and all subsequent operations (including exec)
	// are subject to the policy.
	if err := sandboxInit(policy); err != nil {
		die("hazmat-launch: %v", err)
	}

	execCommand(cmdArgs)
}

func execCommand(cmdArgs []string) {
	// Exec the target command. Since sandbox_init() was called in this
	// process, the sandbox is inherited by the exec'd program.
	// This is a direct exec (no fork) — signals, PTY, and exit codes
	// all work correctly.
	bin, err := resolveExecPath(cmdArgs[0])
	if err != nil {
		die("hazmat-launch: %v", err)
	}

	if err := syscall.Exec(bin, cmdArgs, os.Environ()); err != nil {
		die("hazmat-launch: exec %s: %v", bin, err)
	}
}

func dieUsage() {
	die("usage: hazmat-launch <policy-file> <cmd> [args...]\n       hazmat-launch exec <cmd> [args...]")
}

// sandboxInit calls macOS sandbox_init() with the given SBPL policy string.
// The sandbox applies to this process and is inherited across exec.
func sandboxInit(policy string) error {
	cPolicy := C.CString(policy)
	defer C.free(unsafe.Pointer(cPolicy))

	var errBuf *C.char
	ret := C.sandbox_init(cPolicy, 0, &errBuf)
	if ret != 0 {
		msg := C.GoString(errBuf)
		C.sandbox_free_error(errBuf)
		return fmt.Errorf("sandbox_init: %s", msg)
	}
	return nil
}

// closeInheritedFDs drops every non-stdio descriptor before any helper logic
// runs. sandbox_init() cannot revoke access granted by an already-open handle.
func closeInheritedFDs() error {
	var limit unix.Rlimit
	if err := unix.Getrlimit(unix.RLIMIT_NOFILE, &limit); err != nil {
		return fmt.Errorf("getrlimit RLIMIT_NOFILE: %w", err)
	}

	for fd := 3; fd < int(limit.Cur); fd++ {
		if err := unix.Close(fd); err != nil && err != unix.EBADF {
			return fmt.Errorf("close fd %d: %w", fd, err)
		}
	}
	return nil
}

// resolveExecPath finds the absolute path for a command. syscall.Exec
// requires an absolute path — it doesn't search PATH.
func resolveExecPath(cmd string) (string, error) {
	if cmd[0] == '/' {
		return cmd, nil
	}
	// Search PATH
	for _, dir := range splitPath(os.Getenv("PATH")) {
		full := dir + "/" + cmd
		if info, err := os.Stat(full); err == nil && info.Mode()&0o111 != 0 {
			return full, nil
		}
	}
	return "", fmt.Errorf("command not found: %s", cmd)
}

func splitPath(path string) []string {
	if path == "" {
		return nil
	}
	var result []string
	start := 0
	for i := 0; i < len(path); i++ {
		if path[i] == ':' {
			if i > start {
				result = append(result, path[start:i])
			}
			start = i + 1
		}
	}
	if start < len(path) {
		result = append(result, path[start:])
	}
	return result
}

// validateAndReadPolicy checks the policy file and returns its contents.
func validateAndReadPolicy(path string) (string, error) {
	// ── Path ──────────────────────────────────────────────────────────────────
	if !policyFilePattern.MatchString(path) {
		return "", fmt.Errorf("policy file must match /private/tmp/hazmat-<pid>.sb, got %q", path)
	}

	// ── Existence and metadata ────────────────────────────────────────────────
	info, err := os.Stat(path)
	if err != nil {
		return "", fmt.Errorf("stat %q: %w", path, err)
	}

	// ── Ownership: must be SUDO_UID (the invoking dr user), not root/agent ─────
	sudoUID, err := strconv.Atoi(os.Getenv("SUDO_UID"))
	if err != nil || sudoUID == 0 {
		return "", fmt.Errorf("SUDO_UID not set or root — not a valid sudo invocation")
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return "", fmt.Errorf("cannot inspect policy file ownership")
	}
	if int(stat.Uid) != sudoUID {
		return "", fmt.Errorf("policy file owner uid %d does not match invoking user uid %d",
			stat.Uid, sudoUID)
	}

	// ── Mode: must be exactly 0644 ────────────────────────────────────────────
	if perm := info.Mode().Perm(); perm != 0o644 {
		return "", fmt.Errorf("policy file has mode %04o, expected 0644", perm)
	}

	// ── Content ──────────────────────────────────────────────────────────────
	data, err := readFileCloexec(path)
	if err != nil {
		return "", fmt.Errorf("read %q: %w", path, err)
	}
	if !bytes.Contains(data, []byte(denyDefaultMarker)) {
		return "", fmt.Errorf("policy file does not contain %q — permissive policies are not allowed", denyDefaultMarker)
	}

	return string(data), nil
}

func readFileCloexec(path string) ([]byte, error) {
	fd, err := unix.Open(path, unix.O_RDONLY|unix.O_CLOEXEC, 0)
	if err != nil {
		return nil, err
	}

	f := os.NewFile(uintptr(fd), path)
	if f == nil {
		_ = unix.Close(fd)
		return nil, fmt.Errorf("wrap fd %d for %q", fd, path)
	}
	defer f.Close()

	return io.ReadAll(f)
}

// validatePolicyFile checks the policy file without reading its full contents.
// Kept for backward compatibility with tests.
func validatePolicyFile(path string) error {
	_, err := validateAndReadPolicy(path)
	return err
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
