package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"golang.org/x/sys/unix"
)

// testFileSeq generates unique numeric suffixes so concurrent/sequential
// subtests can each own a distinct /private/tmp/hazmat-<n>.sb path.
var testFileSeq atomic.Int64

// writePolicyFile creates /private/tmp/hazmat-<seq>.sb with the given
// content and mode.  The path satisfies policyFilePattern.
func writePolicyFile(t *testing.T, content string, mode os.FileMode) string {
	t.Helper()
	seq := testFileSeq.Add(1)
	path := fmt.Sprintf("/private/tmp/hazmat-%d.sb", seq)
	if err := os.WriteFile(path, []byte(content), mode); err != nil {
		t.Fatalf("write policy file: %v", err)
	}
	// Explicit chmod so the mode is exactly what we asked for regardless of
	// the process umask — mirrors what runAgentSeatbeltScript does.
	if err := os.Chmod(path, mode); err != nil {
		t.Fatalf("chmod policy file: %v", err)
	}
	t.Cleanup(func() { os.Remove(path) })
	return path
}

// ── Path pattern ──────────────────────────────────────────────────────────────

func TestValidatePolicyFile_PathPattern(t *testing.T) {
	tests := []struct {
		path    string
		wantErr bool
	}{
		{"/private/tmp/hazmat-1234.sb", false},
		{"/private/tmp/hazmat-99999.sb", false},
		{"/private/tmp/hazmat-abc.sb", true},          // non-numeric
		{"/tmp/hazmat-1234.sb", true},                 // wrong dir (symlink target)
		{"/private/tmp/evil/../hazmat-1234.sb", true}, // traversal
		{"/private/tmp/hazmat-.sb", true},             // empty PID component
		{"/private/tmp/xhazmat-1234.sb", true},        // wrong prefix
	}
	for _, tc := range tests {
		got := policyFilePattern.MatchString(tc.path)
		if tc.wantErr && got {
			t.Errorf("path %q: expected pattern to NOT match, but it did", tc.path)
		}
		if !tc.wantErr && !got {
			t.Errorf("path %q: expected pattern to match, but it did not", tc.path)
		}
	}
}

// ── Content check ─────────────────────────────────────────────────────────────

const (
	goodPolicy  = ";; Generated by hazmat\n(version 1)\n(deny default)\n(allow process-fork)\n"
	badPolicy   = "(version 1)\n(allow default)\n"
	emptyPolicy = ""
)

func TestValidatePolicyFile_ContentCheck(t *testing.T) {
	// Set SUDO_UID so the ownership check sees us as the invoking user.
	t.Setenv("SUDO_UID", fmt.Sprint(os.Getuid()))

	t.Run("deny-default passes", func(t *testing.T) {
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err != nil {
			t.Errorf("unexpected error for good policy: %v", err)
		}
	})

	t.Run("allow-default rejected", func(t *testing.T) {
		path := writePolicyFile(t, badPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for allow-default policy, got nil")
		}
	})

	t.Run("empty policy rejected", func(t *testing.T) {
		path := writePolicyFile(t, emptyPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for empty policy, got nil")
		}
	})

	t.Run("wrong mode rejected", func(t *testing.T) {
		path := writePolicyFile(t, goodPolicy, 0o600)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for 0600 mode, got nil")
		}
	})
}

// ── Ownership check ───────────────────────────────────────────────────────────

func TestValidatePolicyFile_OwnershipCheck(t *testing.T) {
	t.Run("matching SUDO_UID passes", func(t *testing.T) {
		t.Setenv("SUDO_UID", fmt.Sprint(os.Getuid()))
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err != nil {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("wrong SUDO_UID rejected", func(t *testing.T) {
		if os.Getuid() == 9999 {
			t.Skip("running as uid 9999")
		}
		t.Setenv("SUDO_UID", "9999")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for mismatched SUDO_UID, got nil")
		}
	})

	t.Run("missing SUDO_UID rejected", func(t *testing.T) {
		t.Setenv("SUDO_UID", "")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for missing SUDO_UID, got nil")
		}
	})

	t.Run("root SUDO_UID rejected", func(t *testing.T) {
		t.Setenv("SUDO_UID", "0")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for SUDO_UID=0, got nil")
		}
	})
}

func TestCloseInheritedFDs_ClosesExtraFiles(t *testing.T) {
	const childEnv = "HAZMAT_LAUNCH_TEST_CHILD"

	if os.Getenv(childEnv) == "1" {
		if err := closeInheritedFDs(); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
		openFDs, err := listOpenFDs(6)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(3)
		}
		if err := json.NewEncoder(os.Stdout).Encode(openFDs); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(4)
		}
		os.Exit(0)
	}

	sentinel, err := os.CreateTemp(t.TempDir(), "hazmat-launch-fd-*")
	if err != nil {
		t.Fatalf("create sentinel file: %v", err)
	}
	defer sentinel.Close()

	if _, err := unix.FcntlInt(sentinel.Fd(), unix.F_SETFD, 0); err != nil {
		t.Fatalf("clear FD_CLOEXEC on sentinel: %v", err)
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestCloseInheritedFDs_ClosesExtraFiles$")
	cmd.Env = append(os.Environ(), childEnv+"=1")
	cmd.ExtraFiles = []*os.File{sentinel}

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("run helper child: %v\n%s", err, out)
	}

	var openFDs []int
	if err := json.Unmarshal(out, &openFDs); err != nil {
		t.Fatalf("decode open fds %q: %v", out, err)
	}

	if want := []int{0, 1, 2}; !reflect.DeepEqual(openFDs, want) {
		t.Fatalf("open fds after cleanup = %v, want %v", openFDs, want)
	}
}

func TestExecModeBypassesPolicyValidation(t *testing.T) {
	const childEnv = "HAZMAT_LAUNCH_EXEC_CHILD"

	if os.Getenv(childEnv) == "1" {
		os.Args = []string{"hazmat-launch", "exec", "/usr/bin/true"}
		main()
		os.Exit(99)
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestExecModeBypassesPolicyValidation$")
	cmd.Env = append(os.Environ(), childEnv+"=1")

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("run exec-mode child: %v\n%s", err, out)
	}
	if got := string(out); got != "" {
		t.Fatalf("exec-mode child output = %q, want empty output", got)
	}
}

func TestLaunchProfileArgParsing(t *testing.T) {
	args := []string{"--hazmat-launch-profile", "/private/tmp/hazmat-1.sb", "/usr/bin/true"}
	if !launchProfileRequested(args) {
		t.Fatal("launch profile flag should be detected")
	}
	if got := stripLaunchProfileArg(args); !reflect.DeepEqual(got, args[1:]) {
		t.Fatalf("stripLaunchProfileArg() = %v, want %v", got, args[1:])
	}
	plain := []string{"/private/tmp/hazmat-1.sb", "/usr/bin/true"}
	if launchProfileRequested(plain) {
		t.Fatal("plain launch args should not enable profile")
	}
	if got := stripLaunchProfileArg(plain); !reflect.DeepEqual(got, plain) {
		t.Fatalf("stripLaunchProfileArg() = %v, want %v", got, plain)
	}
}

func TestLaunchProfileWritesSpans(t *testing.T) {
	var stderr bytes.Buffer
	savedStderr := profileStderr
	profileStderr = &stderr
	t.Cleanup(func() { profileStderr = savedStderr })

	profile := &launchProfile{enabled: true}
	profile.Record("phase", time.Now().Add(-time.Second))
	profile.Done()

	got := stderr.String()
	for _, want := range []string{
		"hazmat-launch: helper profile:",
		"  phase:",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("profile output missing %q in:\n%s", want, got)
		}
	}
}

func TestParseLaunchModeArgsMetadata(t *testing.T) {
	parsed, err := parseLaunchModeArgs([]string{
		"--hazmat-metadata-json",
		`{"kind":"hazmat.session"}`,
		"/usr/bin/env",
		"-i",
	})
	if err != nil {
		t.Fatalf("parseLaunchModeArgs: %v", err)
	}
	if parsed.MetadataJSON != `{"kind":"hazmat.session"}` {
		t.Fatalf("metadata = %q", parsed.MetadataJSON)
	}
	if !reflect.DeepEqual(parsed.CmdArgs, []string{"/usr/bin/env", "-i"}) {
		t.Fatalf("cmdArgs = %v", parsed.CmdArgs)
	}

	if _, err := parseLaunchModeArgs([]string{"--hazmat-metadata-json", `{}`}); err == nil {
		t.Fatal("expected missing command after metadata to be rejected")
	}
	if _, err := parseLaunchModeArgs(nil); err == nil {
		t.Fatal("expected missing command to be rejected")
	}
}

func TestParseLaunchModeArgsDirectExec(t *testing.T) {
	parsed, err := parseLaunchModeArgs([]string{
		"--hazmat-metadata-json",
		`{"kind":"hazmat.session"}`,
		"--hazmat-direct-exec",
		"--hazmat-working-dir",
		"/Users/dr/workspace/project",
		"--hazmat-env",
		"HOME=/Users/agent",
		"--hazmat-env",
		"PATH=/usr/bin",
		"--",
		"/usr/bin/true",
	})
	if err != nil {
		t.Fatalf("parseLaunchModeArgs: %v", err)
	}
	if !parsed.DirectExec {
		t.Fatal("DirectExec = false, want true")
	}
	if parsed.WorkingDir != "/Users/dr/workspace/project" {
		t.Fatalf("WorkingDir = %q", parsed.WorkingDir)
	}
	if !reflect.DeepEqual(parsed.EnvPairs, []string{"HOME=/Users/agent", "PATH=/usr/bin"}) {
		t.Fatalf("EnvPairs = %v", parsed.EnvPairs)
	}
	if !reflect.DeepEqual(parsed.CmdArgs, []string{"/usr/bin/true"}) {
		t.Fatalf("CmdArgs = %v", parsed.CmdArgs)
	}
}

func TestParseLaunchModeArgsDirectExecRequiresWorkingDir(t *testing.T) {
	if _, err := parseLaunchModeArgs([]string{"--hazmat-direct-exec", "--", "/usr/bin/true"}); err == nil {
		t.Fatal("expected direct exec without working dir to be rejected")
	}
}

func TestResolveExecPathHandlesRelativeExecutablePath(t *testing.T) {
	dir := t.TempDir()
	bin := filepath.Join(dir, "tool")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatalf("write executable: %v", err)
	}
	previous, err := os.Getwd()
	if err != nil {
		t.Fatalf("get cwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir temp dir: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(previous); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	})

	got, err := resolveExecPath("./tool")
	if err != nil {
		t.Fatalf("resolveExecPath: %v", err)
	}
	want, err := filepath.Abs("./tool")
	if err != nil {
		t.Fatalf("abs executable: %v", err)
	}
	if got != want {
		t.Fatalf("resolveExecPath = %q, want %q", got, want)
	}
}

func TestFDOpeningCallsUseExplicitCloexec(t *testing.T) {
	fset := token.NewFileSet()
	files, err := filepath.Glob("*.go")
	if err != nil {
		t.Fatalf("glob Go files: %v", err)
	}

	var findings []string
	for _, path := range files {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			ast.Inspect(fn.Body, func(node ast.Node) bool {
				call, ok := node.(*ast.CallExpr)
				if !ok {
					return true
				}
				name := selectorCallName(call.Fun)
				if name == "" {
					return true
				}
				if err := validateFDOpeningCall(fn.Name.Name, call, name); err != nil {
					pos := fset.Position(call.Pos())
					findings = append(findings, fmt.Sprintf("%s: %v", pos, err))
				}
				return true
			})
		}
	}

	if len(findings) > 0 {
		t.Fatalf("hazmat-launch fd-opening guard failed:\n%s", strings.Join(findings, "\n"))
	}
}

func selectorCallName(expr ast.Expr) string {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name + "." + sel.Sel.Name
}

func validateFDOpeningCall(funcName string, call *ast.CallExpr, name string) error {
	switch name {
	case "unix.Open":
		if len(call.Args) < 2 || !exprMentionsSelector(call.Args[1], "unix", "O_CLOEXEC") {
			return fmt.Errorf("%s must include unix.O_CLOEXEC in flags", name)
		}
	case "unix.Openat":
		if len(call.Args) < 3 || !exprMentionsSelector(call.Args[2], "unix", "O_CLOEXEC") {
			return fmt.Errorf("%s must include unix.O_CLOEXEC in flags", name)
		}
	case "syscall.Open":
		if len(call.Args) < 2 || !exprMentionsSelector(call.Args[1], "syscall", "O_CLOEXEC") {
			return fmt.Errorf("%s must include syscall.O_CLOEXEC in flags", name)
		}
	case "os.NewFile":
		if funcName != "readDirCloexec" && funcName != "readFileCloexec" {
			return fmt.Errorf("%s is allowed only inside audited CLOEXEC wrappers", name)
		}
	case "os.Open", "os.OpenFile", "os.Create", "os.CreateTemp",
		"os.ReadFile", "os.ReadDir", "os.WriteFile",
		"unix.Socket", "unix.Socketpair", "syscall.Socket", "syscall.Socketpair":
		return fmt.Errorf("%s creates an fd without explicit CLOEXEC intent; add an audited CLOEXEC wrapper", name)
	}
	return nil
}

func exprMentionsSelector(expr ast.Expr, pkg, name string) bool {
	found := false
	ast.Inspect(expr, func(node ast.Node) bool {
		if found {
			return false
		}
		sel, ok := node.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != name {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if ok && ident.Name == pkg {
			found = true
			return false
		}
		return true
	})
	return found
}

func listOpenFDs(maxFD int) ([]int, error) {
	openFDs := make([]int, 0, maxFD+1)
	for fd := 0; fd <= maxFD; fd++ {
		if _, err := unix.FcntlInt(uintptr(fd), unix.F_GETFD, 0); err != nil {
			if errors.Is(err, unix.EBADF) {
				continue
			}
			return nil, fmt.Errorf("inspect fd %d: %w", fd, err)
		}
		openFDs = append(openFDs, fd)
	}
	return openFDs, nil
}
