package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"
)

// ── Embedded content ──────────────────────────────────────────────────────────

const pfAnchorContent = `# =============================================================
# Soft blocklist for the "agent" user
# Block known-bad ports/protocols; allow everything else
# Generated by hazmat init
# =============================================================

# --- Block exfiltration / C2 protocols ---

# SMTP (email exfiltration)
block return out quick proto tcp from any to any port { 25, 465, 587 } user agent

# IRC (C2 channel)
block return out quick proto tcp from any to any port { 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6697 } user agent

# FTP (legacy file transfer)
block return out quick proto tcp from any to any port { 20, 21 } user agent

# Telnet (insecure remote access)
block return out quick proto tcp from any to any port 23 user agent

# SMB (lateral movement)
block return out quick proto tcp from any to any port 445 user agent

# RDP (remote desktop)
block return out quick proto tcp from any to any port 3389 user agent

# VNC (remote desktop)
block return out quick proto tcp from any to any port { 5900, 5901 } user agent

# Tor (anonymous exfiltration)
block return out quick proto tcp from any to any port { 9050, 9150 } user agent

# SOCKS proxy
block return out quick proto tcp from any to any port 1080 user agent

# VPN protocols
block return out quick proto tcp from any to any port { 1194, 1723 } user agent
block return out quick proto udp from any to any port { 1194, 1723, 4500 } user agent

# XMPP (messaging / C2)
block return out quick proto tcp from any to any port { 5222, 5269 } user agent

# --- Block ICMP tunneling ---
block return out quick proto icmp from any to any user agent

# --- Allow everything else ---
pass out quick user agent
`

const pfDaemonPlistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.local.pf-agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>/sbin/pfctl</string>
        <string>-f</string>
        <string>/etc/pf.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/pf-agent.log</string>
</dict>
</plist>
`

// pfConfAddition is appended to /etc/pf.conf to register the anchor.
// Leading newline provides a blank-line separator from existing content.
const pfConfAddition = `
# Claude Code hazmat user blocklist
anchor "agent"
load anchor "agent" from "/etc/pf.anchors/agent"
`

// seatbeltWrapperContent is the Claude launch wrapper installed at
// seatbeltWrapperPath. Hazmat prepares it during init so the Claude harness can
// be added later without rewriting the base shell environment.
//
// It is aliased to `claude` inside agent-shell sessions. The outer
// sandbox-exec confinement applied by `hazmat shell/exec/claude` already
// covers the session, so this wrapper simply execs the claude binary directly.
const seatbeltWrapperContent = `#!/bin/bash
# claude-sandboxed — launch Claude Code inside the agent sandbox.
# Installed by hazmat init — do not edit manually.
#
# This wrapper is aliased to "claude" in the agent shell. It runs inside a
# The session is already confined by sandbox-exec (started via "hazmat shell"
# or "hazmat claude"), so no additional seatbelt policy is applied here.
set -euo pipefail

CLAUDE_BIN=/Users/agent/.local/bin/claude

if [[ ! -x "$CLAUDE_BIN" ]]; then
    printf 'error: claude binary not found: %s\n' "$CLAUDE_BIN" >&2
    exit 1
fi

exec "$CLAUDE_BIN" "$@"
`

const hostsBlocklistContent = `
# === AI Agent Blocklist ===
# Tunnel services
0.0.0.0 ngrok.io
0.0.0.0 ngrok.com
0.0.0.0 ngrok-free.app
0.0.0.0 tunnel.cloudflare.com
0.0.0.0 trycloudflare.com
0.0.0.0 serveo.net
0.0.0.0 localtunnel.me
0.0.0.0 localhost.run
0.0.0.0 localxpose.io
0.0.0.0 pagekite.me
0.0.0.0 bore.digital
0.0.0.0 localtonet.com
0.0.0.0 zrok.io
0.0.0.0 devtunnels.ms
0.0.0.0 loca.lt
0.0.0.0 tunnelmole.com
0.0.0.0 playit.gg
0.0.0.0 pinggy.io
0.0.0.0 lokal.so
0.0.0.0 telebit.cloud
0.0.0.0 loophole.cloud
# Paste services
0.0.0.0 pastebin.com
0.0.0.0 paste.ee
0.0.0.0 ghostbin.com
0.0.0.0 hastebin.com
0.0.0.0 dpaste.org
0.0.0.0 justpaste.it
0.0.0.0 rentry.co
0.0.0.0 ix.io
# File sharing
0.0.0.0 transfer.sh
0.0.0.0 file.io
0.0.0.0 gofile.io
0.0.0.0 catbox.moe
0.0.0.0 filebin.net
# Webhook capture
0.0.0.0 webhook.site
0.0.0.0 requestbin.com
0.0.0.0 pipedream.com
0.0.0.0 hookbin.com
0.0.0.0 beeceptor.com
# Known supply-chain C2 domains
# axios compromise (2026) — axios/axios#10604
0.0.0.0 sfrclak.com
# === End AI Agent Blocklist ===
`

// ── Command ───────────────────────────────────────────────────────────────────

const initBootstrapSkip = "skip"

func newInitCmd() *cobra.Command {
	var agentUIDFlag, sharedGIDFlag, bootstrapAgentFlag string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Set up containment and optionally bootstrap an AI coding agent",
		Long: `One command to go from fresh macOS to contained agent execution on your Mac.

Creates a dedicated agent user, workspace ACLs, pf port blocklist, DNS
blocklist, seatbelt profile, and automatic snapshots. You can optionally
bootstrap a supported AI coding agent during setup, or skip that step and
install one later.

After init completes:   cd your-project && hazmat shell

Interactive by default — prompts for confirmation before making changes.

  hazmat init                                 # Interactive (recommended)
  hazmat init --bootstrap-agent claude        # Also install Claude Code
  hazmat init --bootstrap-agent codex         # Also install Codex
  hazmat init --yes                           # Non-interactive; skip harness install
  hazmat check                                # Verify the setup
  hazmat rollback                             # Undo everything
  hazmat config agent                         # Configure Claude credentials
  hazmat init cloud                           # Configure S3 cloud backup

Use --dry-run to preview all commands without executing anything.`,
	}
	cmd.Flags().StringVar(&agentUIDFlag, "agent-uid", "",
		"Override UID for the agent user (default: 599; use when 599 is already taken)")
	cmd.Flags().StringVar(&sharedGIDFlag, "group-gid", "",
		"Override GID for the dev group (default: 599; use when 599 is already taken)")
	cmd.Flags().StringVar(&bootstrapAgentFlag, "bootstrap-agent", "",
		"Optional AI coding agent to install during init: skip, claude, codex, opencode")
	cmd.RunE = func(c *cobra.Command, args []string) error {
		if agentUIDFlag != "" {
			agentUID = agentUIDFlag
		}
		if sharedGIDFlag != "" {
			sharedGID = sharedGIDFlag
		}
		return runInit(c, args, bootstrapAgentFlag)
	}
	return cmd
}

// newInitCheckCmd creates the `hazmat check` command.
func newInitCheckCmd() *cobra.Command {
	var full bool
	cmd := &cobra.Command{
		Use:   "check",
		Short: "Verify the setup is working",
		Long: `Runs the verification suite to check that containment is correctly configured.

By default runs quick checks (no network traffic). Use --full to include
live network probes that verify firewall rules are active.`,
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runTest(!full) // runTest(quick bool): true = skip network
		},
	}
	cmd.Flags().BoolVar(&full, "full", false, "Include live network probes (sends external traffic)")
	return cmd
}

// newInitCloudCmd wraps cloud setup as `hazmat init cloud`.
func newInitCloudCmd() *cobra.Command {
	return newConfigCloudCmd()
}

// newStatusCmd shows a progress checklist and optionally runs health checks.
func newStatusCmd() *cobra.Command {
	var full bool
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show setup progress and health check",
		Long: `Shows which setup phases are complete and what to do next.
Use --full to run the complete health check suite (same as 'hazmat check --quick').`,
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runStatus(full)
		},
	}
	cmd.Flags().BoolVar(&full, "full", false, "Run full health checks (same as 'hazmat check --quick')")
	return cmd
}

func runStatus(full bool) error {
	fmt.Println()
	cBold.Println("  Hazmat — AI agent containment for macOS")
	fmt.Println()

	containmentConfigured := func() bool {
		if _, err := user.Lookup(agentUser); err != nil {
			return false
		}
		if _, err := os.Stat(sudoersFile); err != nil {
			return false
		}
		if _, err := os.Stat(pfAnchorFile); err != nil {
			return false
		}
		return true
	}
	installedHarnesses := installedManagedHarnesses()
	claudeConfigured := func() bool {
		data, err := os.ReadFile(agentHome + "/.zshrc")
		if err != nil {
			return false
		}
		return strings.Contains(string(data), "ANTHROPIC_API_KEY")
	}

	allDone := containmentConfigured()
	if allDone {
		cGreen.Printf("  [✓] %-24s %s\n", "Containment configured", "hazmat init")
	} else {
		cYellow.Printf("  [→] %-24s %s   ◀ next\n", "Containment configured", "hazmat init")
	}

	if len(installedHarnesses) == 0 {
		cDim.Printf("  [ ] %-24s %s\n", "Agent harness installed", "hazmat bootstrap claude|codex|opencode")
	} else {
		var names []string
		for _, harness := range installedHarnesses {
			names = append(names, harness.Spec.DisplayName)
		}
		cGreen.Printf("  [✓] %-24s %s\n", "Agent harness installed", strings.Join(names, ", "))
	}

	if isManagedHarnessInstalled(HarnessClaude) {
		if claudeConfigured() {
			cGreen.Printf("  [✓] %-24s %s\n", "Claude credentials set", "hazmat config agent")
		} else {
			cYellow.Printf("  [→] %-24s %s\n", "Claude credentials set", "hazmat config agent")
		}
	} else {
		cDim.Printf("  [ ] %-24s %s\n", "Claude credentials set", "optional; needed only for hazmat claude")
	}

	fmt.Println()
	if allDone {
		if len(installedHarnesses) > 0 {
			fmt.Println("  Quick start:")
			fmt.Printf("    cd your-project && %s\n", installedHarnesses[0].LaunchCommand)
		} else {
			fmt.Println("  Core containment is ready.")
			fmt.Println("  Install a harness when needed:")
			fmt.Println("    hazmat bootstrap claude")
			fmt.Println("    hazmat bootstrap codex")
			fmt.Println("    hazmat bootstrap opencode")
			fmt.Println("  Or run contained commands directly:")
			fmt.Println("    cd your-project && hazmat shell")
		}
	} else {
		fmt.Println("  Next step: hazmat init")
	}
	fmt.Println()

	if full {
		ui := &UI{}
		verifySetup(ui)
		if ui.Summary() {
			return fmt.Errorf("health check found failures")
		}
	}

	return nil
}

// runInit is the top-level entry point.  Named return so defer can inspect
// retErr and print the rollback hint — equivalent to shell's "trap ... ERR".
func initBootstrapChoices() []UIChoice {
	choices := []UIChoice{
		{
			Key:         initBootstrapSkip,
			Label:       "Skip harness install",
			Description: "Set up containment only. Install a coding agent later with 'hazmat bootstrap ...'.",
		},
	}
	for _, harness := range managedHarnesses() {
		choices = append(choices, UIChoice{
			Key:         string(harness.Spec.ID),
			Label:       "Install " + harness.Spec.DisplayName,
			Description: fmt.Sprintf("Bootstrap %s during init and make it ready for 'cd your-project && %s'.", harness.Spec.DisplayName, harness.LaunchCommand),
		})
	}
	return choices
}

func normalizeInitBootstrapAgent(selection string) (string, error) {
	normalized := strings.TrimSpace(strings.ToLower(selection))
	switch normalized {
	case "", initBootstrapSkip:
		return initBootstrapSkip, nil
	}
	if _, ok := managedHarnessByID(HarnessID(normalized)); ok {
		return normalized, nil
	}
	return "", fmt.Errorf("invalid --bootstrap-agent %q (expected skip, claude, codex, or opencode)", selection)
}

func resolveInitBootstrapAgent(ui *UI, flagValue string) (string, error) {
	if flagValue != "" {
		return normalizeInitBootstrapAgent(flagValue)
	}
	if !ui.IsInteractive() {
		return initBootstrapSkip, nil
	}
	fmt.Println()
	cBold.Println("  Optional AI coding agent bootstrap")
	fmt.Println("  Pick a harness to install now, or skip and install one later.")
	selection, err := ui.Choose("Select a harness [1-4, Enter for default]:", initBootstrapChoices(), initBootstrapSkip)
	if err != nil {
		return "", err
	}
	return selection, nil
}

func runInitSelectedBootstrap(ui *UI, r *Runner, selection string) error {
	if selection == initBootstrapSkip {
		fmt.Println()
		cDim.Println("  Skipping optional AI coding agent bootstrap.")
		return nil
	}
	harness, ok := managedHarnessByID(HarnessID(selection))
	if !ok {
		return fmt.Errorf("unsupported harness %q", selection)
	}
	return harness.Bootstrap(ui, r)
}

func runInit(_ *cobra.Command, _ []string, bootstrapAgentFlag string) (retErr error) {
	ui := &UI{DryRun: flagDryRun, YesAll: flagYesAll}
	r := NewRunner(ui, flagVerbose, flagDryRun)

	if err := checkPlatform(); err != nil {
		ui.Fatal(err.Error())
	}

	cu, err := user.Current()
	if err != nil {
		return fmt.Errorf("cannot determine current user: %w", err)
	}
	if cu.Username == "root" {
		ui.Fatal("Run as your normal user, not root. The tool uses sudo where needed.")
	}

	ui.Banner(cu.Username)

	if flagDryRun {
		cYellow.Println("  ────────────────────────────────────────────────────")
		cYellow.Println("  DRY RUN — no changes will be made.")
		cYellow.Println("  Shows all commands regardless of current system state.")
		cYellow.Println("  Steps already complete are skipped when run for real.")
		cYellow.Println("  ────────────────────────────────────────────────────")
		fmt.Println()
	} else if !ui.YesAll && !ui.IsInteractive() {
		// Non-TTY without --yes: fail fast with an actionable message rather
		// than silently aborting after the Ask prompt returns false.
		return fmt.Errorf("stdin is not a terminal\nFor non-interactive setup run: hazmat init --yes")
	} else if !ui.Ask("Proceed with setup?") {
		fmt.Println("  Aborted.")
		return nil
	}

	bootstrapSelection, err := resolveInitBootstrapAgent(ui, bootstrapAgentFlag)
	if err != nil {
		return err
	}

	defer func() {
		if retErr != nil && !flagDryRun {
			fmt.Fprintln(os.Stderr)
			cRed.Fprintln(os.Stderr, "Setup interrupted — some steps may be incomplete.")
			fmt.Fprintln(os.Stderr, "See setup-option-a.md § Uninstall / Rollback")
		}
	}()

	if !flagDryRun {
		if err := preflightChecks(cu.Username); err != nil {
			return err
		}
	}

	// ── Migrations: upgrade from older init versions ─────────────────────
	// Must run BEFORE normal setup steps so old artifacts are cleaned up
	// before new ones are created. The TLA+ spec (MC_Migration) proves
	// this preserves AgentContained across all 44,795 reachable states.
	if !flagDryRun {
		if err := runMigrations(ui, r); err != nil {
			return fmt.Errorf("migration failed: %w", err)
		}
	}

	if err := setupAgentUser(ui, r); err != nil {
		return err
	}
	if err := setupDevGroup(ui, r, cu.Username); err != nil {
		return err
	}
	if err := setupHomeDirTraverse(ui, r); err != nil {
		return err
	}
	if err := setupLocalRepo(ui); err != nil {
		return err
	}
	if err := setupHardeningGaps(ui, r); err != nil {
		return err
	}
	if err := setupSeatbelt(ui, r); err != nil {
		return err
	}
	if err := setupUserExperience(ui, r); err != nil {
		return err
	}
	if err := setupGitSafeDirectory(ui, r); err != nil {
		return err
	}
	if err := setupPfFirewall(ui, r); err != nil {
		return err
	}
	if err := setupDNSBlocklist(ui, r); err != nil {
		return err
	}
	if err := setupLaunchDaemon(ui, r); err != nil {
		return err
	}
	if err := setupLaunchHelper(ui, r); err != nil {
		return err
	}
	if err := setupSudoers(ui, r, cu.Username); err != nil {
		return err
	}

	// ── Bootstrap: install selected AI coding agent ─────────────────────────
	if err := runInitSelectedBootstrap(ui, r, bootstrapSelection); err != nil {
		return err
	}

	// Make agent config files and directories group-writable by dev so
	// hazmat commands (config agent, resume, etc.) can modify them without
	// sudo. Both dr and agent are in the dev group. Setgid on directories
	// ensures new content inherits the dev group.
	if !flagDryRun {
		// Files: agent:dev 0660
		for _, path := range []string{
			agentHome + "/.zshrc",
			agentHome + "/.gitconfig",
		} {
			if _, err := os.Stat(path); os.IsNotExist(err) {
				sudo("touch", path) //nolint:errcheck // best-effort within verified init step; step-level errors handled by MC_SetupRollback
			}
			sudo("chown", agentUser+":"+sharedGroup, path) //nolint:errcheck // best-effort ownership
			sudo("chmod", "0660", path)                    //nolint:errcheck // best-effort permissions
		}
		// Directories: agent:dev 2770 (setgid so new content inherits dev group)
		dirs := []string{agentHome + "/.config/git"}
		if bootstrapSelection == string(HarnessClaude) {
			dirs = append(dirs, agentHome+"/.claude", agentHome+"/.claude/projects")
		}
		for _, dir := range dirs {
			sudo("mkdir", "-p", dir)                      //nolint:errcheck // best-effort within verified init step
			sudo("chown", agentUser+":"+sharedGroup, dir) //nolint:errcheck // best-effort ownership
			sudo("chmod", "2770", dir)                    //nolint:errcheck // best-effort permissions
		}
	}

	// ── Agent credentials: Claude API key + git identity ────────────────────
	if !flagDryRun && ui.IsInteractive() && bootstrapSelection == string(HarnessClaude) {
		if err := runConfigAgent(ui); err != nil {
			cYellow.Printf("\n  Agent config skipped: %v\n", err)
			fmt.Println("  Run 'hazmat config agent' later to set credentials.")
		}
	}

	// ── Optional import: portable Claude basics ─────────────────────────────
	if bootstrapSelection == string(HarnessClaude) {
		env, err := defaultClaudeImportEnv()
		if err == nil {
			if err := claudeCodeHarness.ImportBasics(ui, r, env, claudeImportOptions{
				PromptBeforeImport: true,
				ConflictPolicy:     claudeConflictPrompt,
				AllowNoopMessage:   false,
			}); err != nil && !errors.Is(err, errClaudeImportCancelled) {
				cYellow.Printf("\n  Claude basics import skipped: %v\n", err)
				fmt.Println("  Run 'hazmat config import claude' later to retry.")
			}
		}
	}

	if !flagDryRun {
		// Record the version so future inits can detect and migrate.
		if err := saveState(version); err != nil {
			ui.WarnMsg(fmt.Sprintf("Could not save init state: %v", err))
		}
		verifySetup(ui)
		ui.Logo()
	}

	// If cloud backup was configured during this init, remind the user
	// to save the encryption password — it's easy to miss mid-flow.
	cfg, _ := loadConfig()
	if cfg.Backup.Cloud != nil && cfg.Backup.Cloud.Password != "" {
		fmt.Println()
		cYellow.Println("  ┌──────────────────────────────────────────────────┐")
		cYellow.Println("  │  SAVE YOUR CLOUD BACKUP RECOVERY KEY             │")
		cYellow.Println("  └──────────────────────────────────────────────────┘")
		fmt.Println()
		fmt.Printf("    %s\n", cfg.Backup.Cloud.Password)
		fmt.Println()
		cYellow.Println("  You need this key to restore from cloud backup.")
		cYellow.Println("  It cannot be recovered if lost.")
		fmt.Println()
	}

	cGreen.Println("━━━ Setup complete ━━━")
	fmt.Println()
	fmt.Println("  Ready to use:")
	switch bootstrapSelection {
	case string(HarnessClaude), string(HarnessCodex), string(HarnessOpenCode):
		fmt.Printf("    cd your-project && hazmat %s\n", bootstrapSelection)
	default:
		fmt.Println("    cd your-project && hazmat shell")
		fmt.Println("    hazmat bootstrap claude|codex|opencode")
	}
	fmt.Println()
	fmt.Println("  Check status:   hazmat status")
	if bootstrapSelection == string(HarnessClaude) {
		fmt.Println("  Update creds:   hazmat config agent")
		fmt.Println("  Import basics:  hazmat config import claude")
	} else {
		fmt.Println("  Install agent:  hazmat bootstrap claude|codex|opencode")
	}
	fmt.Println("  View config:    hazmat config")
	fmt.Println("  Uninstall:      hazmat rollback")
	fmt.Println()
	return nil
}

// ── Step 1: Agent user ────────────────────────────────────────────────────────

func setupAgentUser(ui *UI, r *Runner) error {
	ui.Step(fmt.Sprintf("Create '%s' user", agentUser))

	if u, err := user.Lookup(agentUser); err == nil {
		ui.SkipDone(fmt.Sprintf("User '%s' already exists (uid=%s)", agentUser, u.Uid))
		return nil
	}

	if taken, err := uidTaken(agentUID); err != nil {
		return fmt.Errorf("check UID: %w", err)
	} else if taken {
		return fmt.Errorf("UID %s is already taken — use: hazmat init --agent-uid <different-uid>", agentUID)
	}

	record := "/Users/" + agentUser
	type reasonedCmd struct {
		reason string
		args   []string
	}
	for _, rc := range []reasonedCmd{
		{"create agent user record", []string{"dscl", ".", "-create", record}},
		{"set agent user shell", []string{"dscl", ".", "-create", record, "UserShell", "/bin/zsh"}},
		{"set agent user UID", []string{"dscl", ".", "-create", record, "UniqueID", agentUID}},
		{"set agent user primary group", []string{"dscl", ".", "-create", record, "PrimaryGroupID", "20"}},
		{"set agent user home directory", []string{"dscl", ".", "-create", record, "NFSHomeDirectory", agentHome}},
	} {
		if err := r.Sudo(rc.reason, rc.args...); err != nil {
			return fmt.Errorf("dscl %v: %w", rc.args[2:], err)
		}
	}
	ui.Ok("User record created")

	if err := r.Sudo("create agent home directory", "mkdir", "-p", agentHome); err != nil {
		return fmt.Errorf("mkdir %s: %w", agentHome, err)
	}
	if err := r.Sudo("set agent home directory ownership", "chown", agentUser+":staff", agentHome); err != nil {
		return fmt.Errorf("chown %s: %w", agentHome, err)
	}
	// createhomedir may exit non-zero even on success; ignore the error.
	r.Sudo("populate agent home directory", "createhomedir", "-c", "-u", agentUser) //nolint:errcheck
	ui.Ok(fmt.Sprintf("Home directory created at %s", agentHome))

	if err := r.Sudo("hide agent from login screen", "dscl", ".", "-create", record, "IsHidden", "1"); err != nil {
		return fmt.Errorf("hide user: %w", err)
	}
	ui.Ok("Hidden from login screen")

	// Auto-generate the agent user password. The account is hidden and
	// only accessed via sudo — the password exists solely because macOS
	// requires every account to have a password hash.
	{
		var password string
		if r.DryRun {
			password = "<random-192bit-base64>"
		} else {
			var err error
			password, err = generateRandomPassword(24) // 192 bits
			if err != nil {
				return fmt.Errorf("generate agent password: %w", err)
			}
		}
		if err := r.Sudo("set agent password", "dscl", ".", "-passwd", "/Users/"+agentUser, password); err != nil {
			return fmt.Errorf("set agent password: %w", err)
		}
		ui.Ok("Password set (auto-generated, login is disabled)")
	}

	if !r.DryRun {
		if _, err := user.Lookup(agentUser); err != nil {
			return fmt.Errorf("user '%s' not found after creation: %w", agentUser, err)
		}
	}
	return nil
}

// ── Step 2: Dev group ─────────────────────────────────────────────────────────

func setupDevGroup(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Create '%s' group", sharedGroup))

	if g, err := user.LookupGroup(sharedGroup); err == nil {
		ui.SkipDone(fmt.Sprintf("Group '%s' already exists (gid=%s)", sharedGroup, g.Gid))
	} else {
		if taken, err := gidTaken(sharedGID); err != nil {
			return fmt.Errorf("check GID: %w", err)
		} else if taken {
			return fmt.Errorf("GID %s is already taken — use: hazmat init --group-gid <different-gid>", sharedGID)
		}

		record := "/Groups/" + sharedGroup
		type reasonedCmd struct {
			reason string
			args   []string
		}
		for _, rc := range []reasonedCmd{
			{"create dev group", []string{"dscl", ".", "-create", record}},
			{"set dev group GID", []string{"dscl", ".", "-create", record, "PrimaryGroupID", sharedGID}},
			{"set dev group description", []string{"dscl", ".", "-create", record, "RealName", "Shared dev workspace"}},
		} {
			if err := r.Sudo(rc.reason, rc.args...); err != nil {
				return fmt.Errorf("dscl %v: %w", rc.args[2:], err)
			}
		}
		ui.Ok(fmt.Sprintf("Group '%s' created (gid=%s)", sharedGroup, sharedGID))
	}

	for _, u := range []string{currentUser, agentUser} {
		member, err := groupMembershipContains(sharedGroup, u)
		if err != nil {
			return err
		}
		if member {
			ui.SkipDone(fmt.Sprintf("%s is already a member of '%s'", u, sharedGroup))
		} else {
			if err := r.Sudo("add "+u+" to dev group", "dscl", ".", "-append",
				"/Groups/"+sharedGroup, "GroupMembership", u); err != nil {
				return fmt.Errorf("add %s to %s: %w", u, sharedGroup, err)
			}
			ui.Ok(fmt.Sprintf("Added %s to '%s'", u, sharedGroup))
		}
	}
	return nil
}

// ── Step 3: Workspace root ────────────────────────────────────────────────────

// setupHomeDirTraverse grants the agent user directory traversal on $HOME
// so it can reach project directories anywhere under the user's home.
// This is a one-time ACL on the home directory itself — it does NOT grant
// read or list access, only execute (traverse).
func setupHomeDirTraverse(ui *UI, r *Runner) error {
	ui.Step("Allow agent to traverse home directory")

	homeDir := os.Getenv("HOME")
	if homeAllowsAgentTraverse(homeDir) {
		if homeHasAgentTraverseACL(homeDir) {
			ui.SkipDone("Home directory ACL already allows agent traversal")
		} else {
			ui.SkipDone("Home directory permissions already allow agent traversal")
		}
	} else {
		if err := r.Sudo("allow agent to traverse home directory",
			"chmod", "+a", homeTraverseACLEntry(), homeDir); err != nil {
			return fmt.Errorf("set home traversal ACL: %w", err)
		}
		ui.Ok("Home directory ACL set — agent can reach project directories")
	}
	return nil
}

// ── Step 3b: Backup scope file ────────────────────────────────────────────────

func setupLocalRepo(ui *UI) error {
	ui.Step("Configure snapshot backup")

	// Write config.yaml with defaults if it doesn't exist yet.
	cfg, _ := loadConfig()
	if _, err := os.Stat(configFilePath); os.IsNotExist(err) {
		if !flagDryRun {
			if err := saveConfig(cfg); err != nil {
				return fmt.Errorf("write config: %w", err)
			}
		}
	}

	if _, err := os.Stat(localConfigFile); err == nil {
		ui.SkipDone(fmt.Sprintf("Snapshot repository already configured at %s", localRepoDir))
	} else if flagDryRun {
		faint.Printf("    $ kopia repository create filesystem --path %s\n", localRepoDir)
	} else {
		if err := initLocalRepo(); err != nil {
			return fmt.Errorf("initialize snapshot repo: %w", err)
		}
		ui.Ok(fmt.Sprintf("Snapshot repository created at %s", localRepoDir))
	}

	printBackupConfig(cfg)

	// Offer cloud setup if interactive, not already configured, and not --yes.
	if cfg.Backup.Cloud == nil && !flagDryRun && !flagYesAll {
		innerUI := &UI{}
		if innerUI.IsInteractive() {
			if innerUI.Ask("Set up cloud backup (S3-compatible)?") {
				if err := runConfigCloud("", "", "", false); err != nil {
					// Non-fatal: user can configure later.
					cYellow.Printf("\n    Cloud setup skipped: %v\n", err)
					fmt.Println("    Configure later: hazmat config cloud")
				}
			}
		}
	}

	return nil
}

func printBackupConfig(cfg HazmatConfig) {
	fmt.Println()
	cDim.Println("    Snapshots are taken automatically before each session.")
	fmt.Println()
	cDim.Printf("    Repository:  %s\n", cfg.Backup.Local.Path)
	cDim.Printf("    Retention:   %d latest, %d daily, %d weekly\n",
		cfg.Backup.Local.Retention.KeepLatest,
		cfg.Backup.Local.Retention.KeepDaily,
		cfg.Backup.Local.Retention.KeepWeekly)
	cDim.Printf("    Excludes:    node_modules/ .venv/ dist/ build/ target/ ...\n")
	if cfg.Backup.Cloud != nil {
		cDim.Printf("    Cloud:       %s/%s\n", cfg.Backup.Cloud.Endpoint, cfg.Backup.Cloud.Bucket)
	}
	cDim.Printf("    Config:      %s\n", configFilePath)
	fmt.Println()
}

// ── Step 4: Hardening gaps ────────────────────────────────────────────────────

func setupHardeningGaps(ui *UI, r *Runner) error {
	ui.Step("Harden known macOS isolation gaps")

	// Docker socket — owned by current user, no sudo needed.
	dockerSock := os.Getenv("HOME") + "/.docker/run/docker.sock"
	if info, err := os.Stat(dockerSock); err == nil && info.Mode()&os.ModeSocket != 0 {
		current := info.Mode().Perm()
		if current == 0o700 {
			ui.SkipDone("Docker socket already restricted (700)")
		} else {
			if err := r.Chmod(dockerSock, 0o700); err != nil {
				return fmt.Errorf("chmod docker socket: %w", err)
			}
			ui.Ok(fmt.Sprintf("Docker socket restricted to owner only (was %04o)", current))
		}
	} else {
		ui.SkipDone("Docker socket not found (Docker Desktop not running or not installed)")
	}

	// Restrictive umask for agent user — use a managed block so rollback is precise.
	agentZshrc := agentHome + "/.zshrc"
	agentZshrcData, _ := r.AgentOutput("cat", agentZshrc)
	if strings.Contains(agentZshrcData, umaskBlockStart) {
		ui.SkipDone("umask 077 already set in agent's .zshrc")
	} else {
		updated := upsertManagedBlock(agentZshrcData, umaskBlockStart, umaskBlockEnd, "umask 077")
		if err := r.SudoWriteFile("write agent umask to .zshrc", agentZshrc, updated); err != nil {
			return fmt.Errorf("set umask in agent .zshrc: %w", err)
		}
		if err := r.Sudo("set agent .zshrc ownership", "chown", agentUser+":staff", agentZshrc); err != nil {
			return fmt.Errorf("chown agent .zshrc: %w", err)
		}
		ui.Ok("Set umask 077 in agent's .zshrc")
	}

	// Restrictive umask for current user — leave the host shell untouched.
	ui.SkipDone("Host shell umask left unchanged")

	return nil
}

// ── Step 5: Seatbelt wrapper ──────────────────────────────────────────────────

func setupSeatbelt(ui *UI, r *Runner) error {
	ui.Step("Install Claude compatibility wrapper")

	// Create the config dir (used by agentEnvPath) and the bin dir.
	if err := r.AsAgent("create seatbelt config directory", "mkdir", "-p", seatbeltProfileDir); err != nil {
		return fmt.Errorf("mkdir %s: %w", seatbeltProfileDir, err)
	}

	wrapperDir := agentHome + "/.local/bin"
	if err := r.AsAgent("create agent bin directory", "mkdir", "-p", wrapperDir); err != nil {
		return fmt.Errorf("mkdir %s: %w", wrapperDir, err)
	}

	// The wrapper is a managed artifact; re-write on every run so setup
	// doubles as an upgrade path.
	if err := r.SudoWriteFile("install seatbelt wrapper", seatbeltWrapperPath, seatbeltWrapperContent); err != nil {
		return fmt.Errorf("write seatbelt wrapper: %w", err)
	}
	if err := r.Sudo("set seatbelt wrapper ownership", "chown", agentUser+":staff", seatbeltWrapperPath); err != nil {
		return fmt.Errorf("chown seatbelt wrapper: %w", err)
	}
	if err := r.Sudo("make seatbelt wrapper executable", "chmod", "755", seatbeltWrapperPath); err != nil {
		return fmt.Errorf("chmod seatbelt wrapper: %w", err)
	}
	ui.Ok(fmt.Sprintf("Seatbelt wrapper installed at %s", seatbeltWrapperPath))

	return nil
}

func setupUserExperience(ui *UI, r *Runner) error {
	ui.Step("Install command wrappers and toolchain env")

	for _, dir := range []string{
		defaultAgentCacheHome,
		defaultAgentDataHome,
		agentHome + "/.npm",
	} {
		if err := r.AsAgent("create agent directory", "mkdir", "-p", dir); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}

	if err := r.SudoWriteFile("write agent toolchain env", agentEnvPath, agentEnvContent()); err != nil {
		return fmt.Errorf("write agent env file: %w", err)
	}
	if err := r.Sudo("set agent env file ownership", "chown", agentUser+":staff", agentEnvPath); err != nil {
		return fmt.Errorf("chown agent env file: %w", err)
	}
	if err := r.Sudo("set agent env file permissions", "chmod", "644", agentEnvPath); err != nil {
		return fmt.Errorf("chmod agent env file: %w", err)
	}
	ui.Ok(fmt.Sprintf("Agent toolchain env written to %s", agentEnvPath))

	agentZshrc := agentHome + "/.zshrc"
	agentZshrcData, _ := r.AgentOutput("cat", agentZshrc)
	updatedAgentZshrc := upsertManagedBlock(agentZshrcData,
		agentShellBlockStart,
		agentShellBlockEnd,
		`[[ -f "$HOME/.config/hazmat/agent-env.zsh" ]] && source "$HOME/.config/hazmat/agent-env.zsh"`,
	)
	if err := r.SudoWriteFile("write agent shell bootstrap to .zshrc", agentZshrc, updatedAgentZshrc); err != nil {
		return fmt.Errorf("update %s: %w", agentZshrc, err)
	}
	if err := r.Sudo("set agent .zshrc ownership", "chown", agentUser+":staff", agentZshrc); err != nil {
		return fmt.Errorf("chown %s: %w", agentZshrc, err)
	}
	ui.Ok(fmt.Sprintf("Agent shell bootstraps %s", agentEnvPath))

	if err := r.MkdirAll(hostWrapperDir(), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", hostWrapperDir(), err)
	}

	hazmatBin, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve hazmat binary path: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(hazmatBin); err == nil {
		hazmatBin = resolved
	}

	wrappers := []struct {
		name       string
		subcommand string
	}{
		{name: hostClaudeWrapperName, subcommand: "claude"},
		{name: hostExecWrapperName, subcommand: "exec"},
		{name: hostShellWrapperName, subcommand: "shell"},
	}
	for _, wrapper := range wrappers {
		path := hostWrapperPath(wrapper.name)
		if err := r.UserWriteFile(path, hostWrapperContent(hazmatBin, wrapper.subcommand)); err != nil {
			return fmt.Errorf("write wrapper %s: %w", path, err)
		}
		if err := r.Chmod(path, 0o755); err != nil {
			return fmt.Errorf("chmod %s: %w", path, err)
		}
		ui.Ok(fmt.Sprintf("Installed host wrapper %s", path))
	}

	profile, ok := currentUserShellProfile()
	if !ok {
		ui.WarnMsg(fmt.Sprintf("Shell %q is not auto-configured — add %s to your PATH manually", filepath.Base(os.Getenv("SHELL")), hostWrapperDir()))
		return nil
	}

	userRCData, _ := os.ReadFile(profile.rcPath)
	if strings.Contains(string(userRCData), userPathBlockStart) {
		ui.SkipDone(fmt.Sprintf("%s already has a hazmat PATH block", profile.rcPath))
		return nil
	}

	updatedUserRC := upsertManagedBlock(string(userRCData),
		userPathBlockStart,
		userPathBlockEnd,
		profile.pathBlockLines...,
	)
	if err := r.MkdirAll(filepath.Dir(profile.rcPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(profile.rcPath), err)
	}
	if err := r.UserWriteFile(profile.rcPath, updatedUserRC); err != nil {
		return fmt.Errorf("update %s: %w", profile.rcPath, err)
	}
	ui.Ok(fmt.Sprintf("Added %s PATH block to %s", hostWrapperDir(), profile.rcPath))

	return nil
}

// ── Step 5b: Install sandbox-launch helper ────────────────────────────────────

// setupLaunchHelper verifies that the sandbox-launch helper is installed at
// launchHelper and has the expected ownership and mode.
//
// The helper is built separately via 'make sandbox-launch && sudo make install-helper'
// (or 'make install').  Setup does not build it automatically — the user must
// have run make install before 'hazmat init'.  If the helper is absent, setup
// prints clear instructions and fails so the sudoers step is never reached with
// an incorrect path.
func setupLaunchHelper(ui *UI, r *Runner) error {
	ui.Step("Verify sandbox-launch helper")

	info, err := os.Stat(launchHelper)
	if err != nil {
		// Helper not installed — print build instructions and fail.
		return fmt.Errorf("%s not found.\n\n"+
			"Build and install the helper before running setup:\n\n"+
			"  cd hazmat\n"+
			"  make hazmat-launch\n"+
			"  sudo make install-helper\n\n"+
			"Then re-run: hazmat init", launchHelper)
	}

	// Must be a regular executable file owned by root.
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file", launchHelper)
	}
	if info.Mode().Perm()&0o111 == 0 {
		return fmt.Errorf("%s is not executable", launchHelper)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok || stat.Uid != 0 {
		return fmt.Errorf("%s must be owned by root (uid 0), got uid %d", launchHelper, stat.Uid)
	}

	ui.Ok(fmt.Sprintf("%s present (root-owned, executable)", launchHelper))

	// Validate syntax: run 'sandbox-launch --help' would exit non-zero since
	// it does not recognise that flag, but the binary must at least exec.
	// Cheapest check: just verify exit code is non-zero but the binary runs.
	_ = r // no runtime action needed; presence + metadata is sufficient
	return nil
}

// ── Step 6: Passwordless sudo ─────────────────────────────────────────────────

func setupSudoers(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Configure passwordless sudo (%s → %s)", currentUser, agentUser))

	entry := fmt.Sprintf("%s ALL=(%s) NOPASSWD: %s\n", currentUser, agentUser, launchHelper)
	if data, err := r.SudoOutput("cat", sudoersFile); err == nil &&
		strings.Contains(data, launchHelper) {
		// The correct narrow rule is already present — nothing to do.
		ui.SkipDone(fmt.Sprintf("Sudoers entry already targets %s", launchHelper))
	} else {
		// Either the file is absent or it contains a broader rule (e.g. the
		// old "NOPASSWD: ALL" from a previous setup run).  Overwrite it with
		// the narrow entry.  This is the upgrade path for existing installs.
		if err == nil && strings.Contains(data, currentUser) {
			ui.WarnMsg(fmt.Sprintf("Existing sudoers entry does not target %s — replacing with narrow rule", launchHelper))
		}
		// Grant passwordless access to exactly sandbox-launch — the narrow
		// helper that validates policy files before calling sandbox-exec.
		// It refuses deny-bypassing policies and checks SUDO_UID ownership.
		// Install and bootstrap steps run under normal sudo (password required).
		if err := r.SudoWriteFile("write sudoers entry for passwordless agent access", sudoersFile, entry); err != nil {
			return fmt.Errorf("write sudoers: %w", err)
		}
		if err := r.Sudo("set sudoers file permissions", "chmod", "440", sudoersFile); err != nil {
			return fmt.Errorf("chmod sudoers: %w", err)
		}
		if err := r.Sudo("validate sudoers syntax", "visudo", "-c", "-f", sudoersFile); err != nil {
			// Validation failed: clean up the invalid file and bail.
			// Direct sudo() here because this is error recovery, not
			// a primary operation — we never want to skip or preview it.
			sudo("rm", "-f", sudoersFile) //nolint:errcheck
			return fmt.Errorf("sudoers syntax invalid — entry removed. Configure manually: %w", err)
		}
		ui.Ok(fmt.Sprintf("Sudoers entry written: %s can run %s as %s without password",
			currentUser, launchHelper, agentUser))
	}

	// Live smoke-test is skipped: 'sandbox-launch' with no args exits 1 (usage
	// error) and 'sudo' with a missing NOPASSWD rule also exits 1 — the two
	// outcomes are indistinguishable without stderr capture in the Runner.
	// The entry was validated by visudo -c above.
	// Run 'hazmat check' after setup to exercise the full passwordless path.
	return nil
}

// ── Step 6: pf firewall ───────────────────────────────────────────────────────

func setupPfFirewall(ui *UI, r *Runner) error {
	ui.Step("Configure pf port blocklist")

	if _, err := os.Stat(pfAnchorFile); err == nil {
		ui.SkipDone(fmt.Sprintf("pf anchor file already exists at %s", pfAnchorFile))
		ui.WarnMsg(fmt.Sprintf("To replace it, delete first: sudo rm %s", pfAnchorFile))
	} else {
		if err := r.SudoWriteFile("write pf firewall anchor rules", pfAnchorFile, pfAnchorContent); err != nil {
			return fmt.Errorf("write pf anchor: %w", err)
		}
		ui.Ok(fmt.Sprintf("Created pf anchor at %s", pfAnchorFile))
	}

	// os.ReadFile is a read — bypasses Runner.
	pfConf, err := os.ReadFile("/etc/pf.conf")
	if err != nil {
		return fmt.Errorf("read /etc/pf.conf: %w", err)
	}
	if strings.Contains(string(pfConf), `anchor "agent"`) {
		ui.SkipDone("Anchor already registered in /etc/pf.conf")
	} else {
		ts := time.Now().Format("20060102150405")
		if err := r.Sudo("backup pf.conf before modification", "cp", "/etc/pf.conf", "/etc/pf.conf.backup."+ts); err != nil {
			return fmt.Errorf("backup pf.conf: %w", err)
		}
		ui.Ok("Backed up /etc/pf.conf")

		if err := r.SudoAppendFile("register pf anchor in system config", "/etc/pf.conf", pfConfAddition); err != nil {
			return fmt.Errorf("append to pf.conf: %w", err)
		}
		ui.Ok("Registered anchor in /etc/pf.conf")
	}

	if err := r.PfctlLoad("reload firewall rules"); err != nil {
		ui.WarnMsg(fmt.Sprintf("pfctl failed to load rules: %v", err))
	} else {
		ui.Ok("pf rules loaded")
	}
	// pfctl -e returns 1 if already enabled — not an error, ignore it.
	r.Sudo("enable packet filter", "pfctl", "-e") //nolint:errcheck
	ui.Ok("pf enabled")
	return nil
}

// ── Step 7: DNS blocklist ─────────────────────────────────────────────────────

func setupDNSBlocklist(ui *UI, r *Runner) error {
	ui.Step("Configure DNS domain blocklist")

	// os.ReadFile is a read — bypasses Runner.
	hosts, err := os.ReadFile("/etc/hosts")
	if err != nil {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	if strings.Contains(string(hosts), hostsMarker) {
		ui.SkipDone("DNS blocklist already present in /etc/hosts")
		ui.WarnMsg(fmt.Sprintf("To replace it, remove the block between '%s' markers first.", hostsMarker))
		return nil
	}

	if err := r.SudoAppendFile("add DNS blocklist to system hosts file", "/etc/hosts", hostsBlocklistContent); err != nil {
		return fmt.Errorf("append to /etc/hosts: %w", err)
	}

	// Cache flush is fire-and-forget; ignore errors.
	r.Sudo("flush DNS cache", "dscacheutil", "-flushcache")             //nolint:errcheck
	r.Sudo("restart mDNSResponder", "killall", "-HUP", "mDNSResponder") //nolint:errcheck
	ui.Ok("DNS blocklist added to /etc/hosts and cache flushed")
	ui.WarnMsg("This is system-wide. /etc/hosts does not block subdomains.")
	ui.WarnMsg("For wildcard blocking (*.ngrok.io), use dnsmasq — see soft-pf-blocklist.md")
	return nil
}

// ── Step 8: LaunchDaemon ──────────────────────────────────────────────────────

func setupLaunchDaemon(ui *UI, r *Runner) error {
	ui.Step("Persist firewall across reboots")

	if _, err := os.Stat(pfDaemonPlist); err == nil {
		ui.SkipDone(fmt.Sprintf("LaunchDaemon already exists at %s", pfDaemonPlist))
		return nil
	}

	if err := r.SudoWriteFile("install firewall persistence daemon", pfDaemonPlist, pfDaemonPlistContent); err != nil {
		return fmt.Errorf("write LaunchDaemon plist: %w", err)
	}
	if err := r.Sudo("set launch daemon permissions", "chmod", "644", pfDaemonPlist); err != nil {
		return fmt.Errorf("chmod plist: %w", err)
	}
	if err := r.LaunchctlBootstrap("start firewall persistence daemon", pfDaemonPlist); err != nil {
		ui.WarnMsg(fmt.Sprintf("launchctl bootstrap: %v — plist written but not loaded", err))
	} else {
		ui.Ok("LaunchDaemon installed — pf rules will reload on boot")
	}
	return nil
}

// ── Verify ────────────────────────────────────────────────────────────────────

// verifySetup re-checks key invariants after all steps complete.
// All operations here are read-only; no Runner needed.
// Uses TestPass/TestFail/TestWarn so callers (hazmat status) can check
// ui.Fail > 0 and return a non-zero exit code when the sandbox is broken.
func verifySetup(ui *UI) {
	ui.Step("Verify setup")
	fmt.Println()

	if u, err := user.Lookup(agentUser); err == nil {
		ui.TestPass(fmt.Sprintf("User '%s' exists (uid=%s)", agentUser, u.Uid))
	} else {
		ui.TestFail(fmt.Sprintf("User '%s' not found", agentUser))
	}

	if _, err := os.Stat(agentHome); err == nil {
		ui.TestPass(fmt.Sprintf("Home directory exists at %s", agentHome))
	} else {
		ui.TestFail(fmt.Sprintf("Home directory missing: %s", agentHome))
	}

	homeDir := os.Getenv("HOME")
	if homeAllowsAgentTraverse(homeDir) {
		ui.TestPass(fmt.Sprintf("Home directory ACL lets '%s' traverse to project directories", agentUser))
	} else {
		ui.TestWarn(fmt.Sprintf("Home directory access for '%s' not detected — project directories may be inaccessible", agentUser))
	}

	if out, err := sudoOutput("pfctl", "-a", pfAnchorName, "-sr"); err == nil &&
		strings.Contains(out, "block") {
		n := len(strings.Split(strings.TrimSpace(out), "\n"))
		ui.TestPass(fmt.Sprintf("pf anchor loaded with %d rules", n))
	} else {
		ui.TestFail("pf anchor not loaded or empty — try: sudo pfctl -f /etc/pf.conf && sudo pfctl -e")
	}

	if out, err := sudoOutput("pfctl", "-si"); err == nil &&
		strings.Contains(out, "Status: Enabled") {
		ui.TestPass("pf is enabled")
	} else {
		ui.TestFail("pf is not enabled — run: sudo pfctl -e")
	}

	if err := sudo("-u", agentUser, "whoami"); err == nil {
		ui.TestPass(fmt.Sprintf("Passwordless sudo works (%s → %s)", os.Getenv("USER"), agentUser))
	} else {
		ui.TestFail("Passwordless sudo not working")
	}

	// DNS blocklist is optional — was a prompted step during setup.
	if data, err := os.ReadFile("/etc/hosts"); err == nil &&
		strings.Contains(string(data), "AI Agent Blocklist") {
		n := strings.Count(string(data), "0.0.0.0 ")
		ui.TestPass(fmt.Sprintf("DNS blocklist active (%d domains in /etc/hosts)", n))
	} else {
		ui.TestWarn("DNS blocklist not installed in /etc/hosts (optional — see setup-option-a.md)")
	}

	if info, err := os.Stat(seatbeltWrapperPath); err == nil && info.Mode()&0o111 != 0 {
		ui.TestPass(fmt.Sprintf("Seatbelt wrapper installed and executable at %s", seatbeltWrapperPath))
	} else {
		ui.TestFail(fmt.Sprintf("Seatbelt wrapper missing or not executable: %s", seatbeltWrapperPath))
	}

	// Agent shell env is advisory — wrappers work without it but PATH and
	// aliases inside agent-shell will be incomplete.
	if _, err := os.Stat(agentEnvPath); err == nil {
		ui.TestPass(fmt.Sprintf("Agent shell env installed at %s", agentEnvPath))
	} else {
		ui.TestWarn(fmt.Sprintf("Agent shell env missing: %s", agentEnvPath))
	}

	for _, wrapper := range []string{hostClaudeWrapperName, hostExecWrapperName, hostShellWrapperName} {
		path := hostWrapperPath(wrapper)
		if info, err := os.Stat(path); err == nil && info.Mode()&0o111 != 0 {
			ui.TestPass(fmt.Sprintf("Host wrapper installed: %s", path))
		} else {
			ui.TestFail(fmt.Sprintf("Host wrapper missing or not executable: %s", path))
		}
	}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// preflightChecks validates that all prerequisites are met before making any
// system changes. This catches problems like missing hazmat-launch or UID
// conflicts before setup modifies 13 system files.
func preflightChecks(currentUser string) error {
	type check struct {
		label string
		fn    func() error
	}

	checks := []check{
		{"macOS detected", checkPlatform},
		{"hazmat-launch installed", func() error {
			info, err := os.Stat(launchHelper)
			if err != nil {
				return fmt.Errorf("%s not found\n\n"+
					"Build and install the helper before running setup:\n\n"+
					"  cd hazmat\n"+
					"  make hazmat-launch\n"+
					"  sudo make install-helper", launchHelper)
			}
			if !info.Mode().IsRegular() || info.Mode().Perm()&0o111 == 0 {
				return fmt.Errorf("%s is not an executable file", launchHelper)
			}
			return nil
		}},
		{"UID " + agentUID + " available", func() error {
			if _, err := user.Lookup(agentUser); err == nil {
				return nil // agent user already exists — fine
			}
			if taken, err := uidTaken(agentUID); err != nil {
				return fmt.Errorf("cannot check UID: %w", err)
			} else if taken {
				return fmt.Errorf("UID %s is already taken — use: hazmat init --agent-uid <different-uid>", agentUID)
			}
			return nil
		}},
		{"GID " + sharedGID + " available", func() error {
			if _, err := user.LookupGroup(sharedGroup); err == nil {
				return nil // group already exists — fine
			}
			if taken, err := gidTaken(sharedGID); err != nil {
				return fmt.Errorf("cannot check GID: %w", err)
			} else if taken {
				return fmt.Errorf("GID %s is already taken — use: hazmat init --group-gid <different-gid>", sharedGID)
			}
			return nil
		}},
	}

	fmt.Println("  Pre-flight checks:")
	for _, c := range checks {
		if err := c.fn(); err != nil {
			cRed.Printf("  ✗ %s\n", c.label)
			return fmt.Errorf("pre-flight check failed: %w", err)
		}
		cGreen.Printf("  ✓ %s\n", c.label)
	}
	fmt.Println()
	return nil
}

func checkPlatform() error {
	cmd := exec.Command("uname")
	out, err := cmd.Output()
	if err != nil || strings.TrimSpace(string(out)) != "Darwin" {
		return fmt.Errorf("this tool is for macOS only")
	}
	return nil
}

func uidTaken(uid string) (bool, error) {
	out, err := dscl("-list", "/Users", "UniqueID")
	if err != nil {
		return false, fmt.Errorf("dscl list UIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == uid {
			return true, nil
		}
	}
	return false, nil
}

func gidTaken(gid string) (bool, error) {
	out, err := dscl("-list", "/Groups", "PrimaryGroupID")
	if err != nil {
		return false, fmt.Errorf("dscl list GIDs: %w", err)
	}
	for _, line := range strings.Split(out, "\n") {
		if fields := strings.Fields(line); len(fields) >= 2 && fields[1] == gid {
			return true, nil
		}
	}
	return false, nil
}

func homeTraverseACLEntry() string {
	return "user:" + agentUser + " allow execute,readattr,readextattr,readsecurity"
}

func homeHasAgentTraverseACL(homeDir string) bool {
	out, err := exec.Command("ls", "-led", homeDir).CombinedOutput()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "user:"+agentUser) &&
		strings.Contains(string(out), " allow execute")
}

func homeAllowsAgentTraverse(homeDir string) bool {
	if homeHasAgentTraverseACL(homeDir) {
		return true
	}

	info, err := os.Stat(homeDir)
	if err != nil {
		return false
	}
	if info.Mode().Perm()&0o001 != 0 {
		return true
	}
	if info.Mode().Perm()&0o010 == 0 {
		return false
	}

	st, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return false
	}
	group, err := user.LookupGroupId(fmt.Sprintf("%d", st.Gid))
	if err != nil {
		return false
	}
	member, err := groupMembershipContains(group.Name, agentUser)
	if err != nil {
		return false
	}
	return member
}

func groupMembershipContains(group, username string) (bool, error) {
	out, err := dscl("-read", "/Groups/"+group, "GroupMembership")
	if err != nil {
		return false, nil // group exists but has no members yet
	}
	for _, field := range strings.Fields(out) {
		if field == username {
			return true, nil
		}
	}
	return false, nil
}
