//go:build darwin

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

const pfAnchorContent = `# =============================================================
# Soft blocklist for the "agent" user
# Block known-bad ports/protocols; allow everything else
# Generated by hazmat init
# =============================================================

# --- Block exfiltration / C2 protocols ---

# SMTP (email exfiltration)
block return out quick proto tcp from any to any port { 25, 465, 587 } user agent

# IRC (C2 channel)
block return out quick proto tcp from any to any port { 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6697 } user agent

# FTP (legacy file transfer)
block return out quick proto tcp from any to any port { 20, 21 } user agent

# Telnet (insecure remote access)
block return out quick proto tcp from any to any port 23 user agent

# SMB (lateral movement)
block return out quick proto tcp from any to any port 445 user agent

# RDP (remote desktop)
block return out quick proto tcp from any to any port 3389 user agent

# VNC (remote desktop)
block return out quick proto tcp from any to any port { 5900, 5901 } user agent

# Tor (anonymous exfiltration)
block return out quick proto tcp from any to any port { 9050, 9150 } user agent

# SOCKS proxy
block return out quick proto tcp from any to any port 1080 user agent

# VPN protocols
block return out quick proto tcp from any to any port { 1194, 1723 } user agent
block return out quick proto udp from any to any port { 1194, 1723, 4500 } user agent

# XMPP (messaging / C2)
block return out quick proto tcp from any to any port { 5222, 5269 } user agent

# --- Block ICMP tunneling ---
block return out quick proto icmp from any to any user agent

# --- Allow everything else ---
pass out quick user agent
`

const pfDaemonPlistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.local.pf-agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>/sbin/pfctl</string>
        <string>-f</string>
        <string>/etc/pf.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/pf-agent.log</string>
</dict>
</plist>
`

// pfConfAddition is appended to /etc/pf.conf to register the anchor.
// Leading newline provides a blank-line separator from existing content.
const pfConfAddition = `
# Claude Code hazmat user blocklist
anchor "agent"
load anchor "agent" from "/etc/pf.anchors/agent"
`

const hostsBlocklistContent = `
# === AI Agent Blocklist ===
# Tunnel services
0.0.0.0 ngrok.io
0.0.0.0 ngrok.com
0.0.0.0 ngrok-free.app
0.0.0.0 tunnel.cloudflare.com
0.0.0.0 trycloudflare.com
0.0.0.0 serveo.net
0.0.0.0 localtunnel.me
0.0.0.0 localhost.run
0.0.0.0 localxpose.io
0.0.0.0 pagekite.me
0.0.0.0 bore.digital
0.0.0.0 localtonet.com
0.0.0.0 zrok.io
0.0.0.0 devtunnels.ms
0.0.0.0 loca.lt
0.0.0.0 tunnelmole.com
0.0.0.0 playit.gg
0.0.0.0 pinggy.io
0.0.0.0 lokal.so
0.0.0.0 telebit.cloud
0.0.0.0 loophole.cloud
# Paste services
0.0.0.0 pastebin.com
0.0.0.0 paste.ee
0.0.0.0 ghostbin.com
0.0.0.0 hastebin.com
0.0.0.0 dpaste.org
0.0.0.0 justpaste.it
0.0.0.0 rentry.co
0.0.0.0 ix.io
# File sharing
0.0.0.0 transfer.sh
0.0.0.0 file.io
0.0.0.0 gofile.io
0.0.0.0 catbox.moe
0.0.0.0 filebin.net
# Webhook capture
0.0.0.0 webhook.site
0.0.0.0 requestbin.com
0.0.0.0 pipedream.com
0.0.0.0 hookbin.com
0.0.0.0 beeceptor.com
# Known supply-chain C2 domains
# axios compromise (2026) — axios/axios#10604
0.0.0.0 sfrclak.com
# === End AI Agent Blocklist ===
`

type darwinNativeServiceBackend struct{}

func newNativeServiceBackend() nativeServiceBackend {
	return darwinNativeServiceBackend{}
}

func (b darwinNativeServiceBackend) SetupLaunchHelper(ui *UI, r *Runner) error {
	ui.Step("Verify sandbox-launch helper")

	helperPath := launchHelperPath()

	// If not at the final path, try to install from brew.
	if _, err := os.Stat(helperPath); err != nil {
		if helperPath != systemLaunchHelper {
			return fmt.Errorf("%s not found.\n\n"+
				"Install Hazmat before running setup:\n\n"+
				"  make install\n\n"+
				"Or install system-wide:\n\n"+
				"  sudo make install-system\n\n"+
				"Then re-run: hazmat init", helperPath)
		}
		src := b.FindBrewLaunchHelper()
		if src == "" {
			return fmt.Errorf("%s not found.\n\n"+
				"Install Hazmat before running setup:\n\n"+
				"  make install\n\n"+
				"Or install system-wide:\n\n"+
				"  sudo make install-system\n\n"+
				"Then re-run: hazmat init", helperPath)
		}
		ui.WarnMsg(fmt.Sprintf("Installing %s from %s", helperPath, src))
		if err := r.Sudo("create "+filepath.Dir(helperPath),
			"mkdir", "-p", filepath.Dir(helperPath)); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(helperPath), err)
		}
		if err := r.Sudo("install hazmat-launch to "+helperPath,
			"install", "-m", "0755", "-o", "root", src, helperPath); err != nil {
			return fmt.Errorf("install hazmat-launch: %w", err)
		}
	}

	info, err := os.Stat(helperPath)
	if err != nil {
		return fmt.Errorf("%s not found after install attempt", helperPath)
	}

	// Must be a regular executable file.
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file", helperPath)
	}
	if info.Mode().Perm()&0o111 == 0 {
		return fmt.Errorf("%s is not executable", helperPath)
	}

	if helperPath == systemLaunchHelper {
		stat, ok := info.Sys().(*syscall.Stat_t)
		if !ok || stat.Uid != 0 {
			return fmt.Errorf("%s must be owned by root (uid 0), got uid %d", helperPath, stat.Uid)
		}
		ui.Ok(fmt.Sprintf("%s present (root-owned, executable)", helperPath))
		return nil
	}

	if err := ensureAgentCanTraverseLaunchHelper(r, helperPath); err != nil {
		return err
	}

	ui.Ok(fmt.Sprintf("%s present (user-local, executable)", helperPath))
	return nil
}

func (darwinNativeServiceBackend) SetupSudoers(ui *UI, r *Runner, currentUser string) error {
	ui.Step(fmt.Sprintf("Configure passwordless sudo for launch helper (%s → %s)", currentUser, agentUser))
	if err := installLaunchSudoers(ui, r, currentUser); err != nil {
		return err
	}

	// Live smoke-test is skipped: 'sandbox-launch' with no args exits 1 (usage
	// error) and 'sudo' with a missing NOPASSWD rule also exits 1 — the two
	// outcomes are indistinguishable without stderr capture in the Runner.
	// The entry was validated by visudo -c above.
	// Run 'hazmat check' after setup to exercise the full passwordless path.
	return nil
}

func (darwinNativeServiceBackend) MaybeSetupOptionalAgentMaintenanceSudoers(ui *UI, r *Runner, currentUser string) error {
	ui.Step("Optional passwordless sudo for agent maintenance")

	if agentMaintenanceSudoersInstalled() {
		ui.SkipDone(fmt.Sprintf("Optional agent-maintenance sudoers entry already present at %s", agentMaintenanceSudoersFile))
		return nil
	}

	fmt.Println("  Hazmat can also install a broader optional sudoers rule for day-to-day")
	fmt.Println("  manual agent-user commands that bypass Hazmat's helper-backed")
	fmt.Println("  maintenance path and use raw 'sudo -u agent ...' instead.")
	fmt.Println()
	cDim.Println("  This is broader than the default launch-helper rule.")
	cDim.Println("  Only enable it if you want to stop repeated password prompts for")
	cDim.Println("  generic agent-user commands.")
	cDim.Println("  Interactive init leaves this opt-in; 'hazmat init --yes' installs")
	cDim.Println("  it by default for smoother non-interactive use.")
	fmt.Println()

	defaultChoice := agentMaintenanceSudoersDefaultChoice(ui)
	choice, err := ui.Choose(
		"Optional agent-maintenance passwordless sudo:",
		[]UIChoice{
			{
				Key:         "install",
				Label:       "Install opt-in rule",
				Description: "Lets you run raw generic 'sudo -u agent ...' commands without repeated password prompts.",
			},
			{
				Key:         "skip",
				Label:       "Keep narrow default",
				Description: "Leaves generic agent-user commands on normal sudo prompts.",
			},
		},
		defaultChoice,
	)
	if err != nil {
		return err
	}
	if choice != "install" {
		ui.WarnMsg("Leaving generic agent-user commands on standard sudo prompts")
		return nil
	}

	return installAgentMaintenanceSudoers(ui, r, currentUser)
}

func (darwinNativeServiceBackend) SetupPfFirewall(ui *UI, r *Runner) error {
	ui.Step("Configure pf port blocklist")

	if _, err := os.Stat(pfAnchorFile); err == nil {
		ui.SkipDone(fmt.Sprintf("pf anchor file already exists at %s", pfAnchorFile))
		ui.WarnMsg(fmt.Sprintf("To replace it, delete first: sudo rm %s", pfAnchorFile))
	} else {
		if err := r.SudoWriteFile("write pf firewall anchor rules", pfAnchorFile, pfAnchorContent); err != nil {
			return fmt.Errorf("write pf anchor: %w", err)
		}
		ui.Ok(fmt.Sprintf("Created pf anchor at %s", pfAnchorFile))
	}

	// os.ReadFile is a read — bypasses Runner.
	pfConf, err := os.ReadFile("/etc/pf.conf")
	if err != nil {
		return fmt.Errorf("read /etc/pf.conf: %w", err)
	}
	if strings.Contains(string(pfConf), `anchor "agent"`) {
		ui.SkipDone("Anchor already registered in /etc/pf.conf")
	} else {
		ts := time.Now().Format("20060102150405")
		if err := r.Sudo("backup pf.conf before modification", "cp", "/etc/pf.conf", "/etc/pf.conf.backup."+ts); err != nil {
			return fmt.Errorf("backup pf.conf: %w", err)
		}
		ui.Ok("Backed up /etc/pf.conf")

		if err := r.SudoAppendFile("register pf anchor in system config", "/etc/pf.conf", pfConfAddition); err != nil {
			return fmt.Errorf("append to pf.conf: %w", err)
		}
		ui.Ok("Registered anchor in /etc/pf.conf")
	}

	if err := r.PfctlLoad("reload firewall rules"); err != nil {
		ui.WarnMsg(fmt.Sprintf("pfctl failed to load rules: %v", err))
	} else {
		ui.Ok("pf rules loaded")
	}
	// pfctl -e returns 1 if already enabled — not an error, ignore it.
	r.Sudo("enable packet filter", hostPfctlPath, "-e") //nolint:errcheck
	ui.Ok("pf enabled")
	return nil
}

func (darwinNativeServiceBackend) SetupDNSBlocklist(ui *UI, r *Runner) error {
	ui.Step("Configure DNS domain blocklist")

	// os.ReadFile is a read — bypasses Runner.
	hosts, err := os.ReadFile("/etc/hosts")
	if err != nil {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	if strings.Contains(string(hosts), hostsMarker) {
		ui.SkipDone("DNS blocklist already present in /etc/hosts")
		ui.WarnMsg(fmt.Sprintf("To replace it, remove the block between '%s' markers first.", hostsMarker))
		return nil
	}

	if err := r.SudoAppendFile("add DNS blocklist to system hosts file", "/etc/hosts", hostsBlocklistContent); err != nil {
		return fmt.Errorf("append to /etc/hosts: %w", err)
	}

	// Cache flush is fire-and-forget; ignore errors.
	r.Sudo("flush DNS cache", "dscacheutil", "-flushcache")             //nolint:errcheck
	r.Sudo("restart mDNSResponder", "killall", "-HUP", "mDNSResponder") //nolint:errcheck
	ui.Ok("DNS blocklist added to /etc/hosts and cache flushed")
	ui.WarnMsg("This is system-wide. /etc/hosts does not block subdomains.")
	ui.WarnMsg("For wildcard blocking (*.ngrok.io), use dnsmasq — see soft-pf-blocklist.md")
	return nil
}

func (darwinNativeServiceBackend) SetupLaunchDaemon(ui *UI, r *Runner) error {
	ui.Step("Persist firewall across reboots")

	if _, err := os.Stat(pfDaemonPlist); err == nil {
		ui.SkipDone(fmt.Sprintf("LaunchDaemon already exists at %s", pfDaemonPlist))
		return nil
	}

	if err := r.SudoWriteFile("install firewall persistence daemon", pfDaemonPlist, pfDaemonPlistContent); err != nil {
		return fmt.Errorf("write LaunchDaemon plist: %w", err)
	}
	if err := r.Sudo("set launch daemon permissions", "chmod", "644", pfDaemonPlist); err != nil {
		return fmt.Errorf("chmod plist: %w", err)
	}
	if err := r.LaunchctlBootstrap("start firewall persistence daemon", pfDaemonPlist); err != nil {
		ui.WarnMsg(fmt.Sprintf("launchctl bootstrap: %v — plist written but not loaded", err))
	} else {
		ui.Ok("LaunchDaemon installed — pf rules will reload on boot")
	}
	return nil
}

func (darwinNativeServiceBackend) RollbackLaunchDaemon(ui *UI, r *Runner) {
	ui.Step("Remove LaunchDaemon")

	if _, err := os.Stat(pfDaemonPlist); os.IsNotExist(err) {
		ui.SkipDone("LaunchDaemon plist not present")
		return
	}

	// bootout may fail if the daemon was never loaded; ignore the error.
	r.Sudo("unload firewall persistence daemon", hostLaunchctlPath, "bootout", "system", pfDaemonPlist) //nolint:errcheck
	ui.Ok("LaunchDaemon unloaded (or was not loaded)")

	if err := r.Sudo("remove firewall persistence plist", "rm", "-f", pfDaemonPlist); err != nil {
		ui.WarnMsg(fmt.Sprintf("Could not remove %s: %v", pfDaemonPlist, err))
	} else {
		ui.Ok(fmt.Sprintf("Removed %s", pfDaemonPlist))
	}
}

func (darwinNativeServiceBackend) RollbackPfFirewall(ui *UI, r *Runner) {
	ui.Step("Remove pf anchor")

	if _, err := os.Stat(pfAnchorFile); os.IsNotExist(err) {
		ui.SkipDone("pf anchor file not present")
	} else {
		if err := r.Sudo("remove pf anchor file", "rm", "-f", pfAnchorFile); err != nil {
			ui.WarnMsg(fmt.Sprintf("Could not remove %s: %v", pfAnchorFile, err))
		} else {
			ui.Ok(fmt.Sprintf("Removed pf anchor file %s", pfAnchorFile))
		}
	}

	pfConf := "/etc/pf.conf"
	data, err := os.ReadFile(pfConf)
	if err != nil {
		ui.WarnMsg(fmt.Sprintf("Could not read %s: %v", pfConf, err))
		return
	}

	if !strings.Contains(string(data), `anchor "agent"`) {
		ui.SkipDone("/etc/pf.conf does not reference the agent anchor")
		return
	}

	// Prefer restoring from the timestamped backup made during setup.
	backup := latestPfConfBackup()
	if backup != "" {
		if err := r.Sudo("restore original pf.conf from backup", "cp", "-f", backup, pfConf); err != nil {
			ui.WarnMsg(fmt.Sprintf("Could not restore %s from backup %s: %v — stripping lines in place", pfConf, backup, err))
			stripPfAnchorLines(ui, r, pfConf, data)
		} else {
			ui.Ok(fmt.Sprintf("Restored %s from backup %s", pfConf, backup))
		}
	} else {
		ui.WarnMsg("No timestamped backup of /etc/pf.conf found — stripping anchor lines in place")
		stripPfAnchorLines(ui, r, pfConf, data)
	}

	if err := r.PfctlLoad("reload pf rules after anchor removal"); err != nil {
		ui.WarnMsg(fmt.Sprintf("pfctl reload failed: %v", err))
	} else {
		ui.Ok("pf rules reloaded")
	}
}

func (darwinNativeServiceBackend) RollbackDNSBlocklist(ui *UI, r *Runner) {
	ui.Step("Remove DNS blocklist")

	data, err := os.ReadFile("/etc/hosts")
	if err != nil {
		ui.WarnMsg(fmt.Sprintf("Could not read /etc/hosts: %v", err))
		return
	}

	if !strings.Contains(string(data), hostsMarker) {
		ui.SkipDone("DNS blocklist not present in /etc/hosts")
		return
	}

	// Remove lines from hostsMarker through hostsEndMarker, inclusive.
	// The block was appended with a leading \n — trim trailing blank lines after removal.
	const endMarker = "# === End AI Agent Blocklist ==="
	var kept []string
	inside := false
	for _, line := range strings.Split(string(data), "\n") {
		if strings.TrimSpace(line) == hostsMarker {
			inside = true
			continue
		}
		if inside {
			if strings.TrimSpace(line) == endMarker {
				inside = false
			}
			continue
		}
		kept = append(kept, line)
	}

	cleaned := strings.TrimRight(strings.Join(kept, "\n"), "\n") + "\n"
	if err := r.SudoWriteFile("remove DNS blocklist from /etc/hosts", "/etc/hosts", cleaned); err != nil {
		ui.WarnMsg(fmt.Sprintf("Could not update /etc/hosts: %v", err))
		return
	}
	ui.Ok("Removed DNS blocklist from /etc/hosts")

	// Flush DNS cache — fire-and-forget.
	r.Sudo("flush DNS cache after blocklist removal", "dscacheutil", "-flushcache")             //nolint:errcheck
	r.Sudo("restart mDNSResponder after blocklist removal", "killall", "-HUP", "mDNSResponder") //nolint:errcheck
	ui.Ok("DNS cache flushed")
}

func (darwinNativeServiceBackend) RollbackSudoers(ui *UI, r *Runner) {
	ui.Step("Remove sudoers entries")

	removedAny := false
	for _, path := range []string{sudoersFile, agentMaintenanceSudoersFile} {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			continue
		}
		if err := r.Sudo("remove sudoers entry", "rm", "-f", path); err != nil {
			ui.WarnMsg(fmt.Sprintf("Could not remove %s: %v", path, err))
			continue
		}
		ui.Ok(fmt.Sprintf("Removed %s", path))
		removedAny = true
	}
	if !removedAny {
		ui.SkipDone("Sudoers files not present")
	}
}

func (darwinNativeServiceBackend) InstallAgentMaintenanceSudoers(ui *UI, r *Runner, currentUser string) error {
	return installAgentMaintenanceSudoers(ui, r, currentUser)
}

func (darwinNativeServiceBackend) UninstallAgentMaintenanceSudoers(ui *UI, r *Runner) error {
	return uninstallAgentMaintenanceSudoers(ui, r)
}

func (darwinNativeServiceBackend) LaunchSudoersInstalled() bool {
	_, err := os.Stat(sudoersFile)
	return err == nil
}

func (darwinNativeServiceBackend) AgentMaintenanceSudoersInstalled() bool {
	_, err := os.Stat(agentMaintenanceSudoersFile)
	return err == nil
}

func (darwinNativeServiceBackend) GenericAgentPasswordlessAvailable() bool {
	return sudoNoPrompt("-u", agentUser, "whoami") == nil
}

func (darwinNativeServiceBackend) FindBrewLaunchHelper() string {
	for _, p := range brewLaunchHelperPaths {
		if info, err := os.Stat(p); err == nil && info.Mode().IsRegular() {
			return p
		}
	}
	return ""
}

// brewLaunchHelperPaths lists known locations where Homebrew may place hazmat-launch.
var brewLaunchHelperPaths = []string{
	"/opt/homebrew/opt/hazmat/libexec/hazmat-launch", // Apple Silicon
	"/usr/local/opt/hazmat/libexec/hazmat-launch",    // Intel
}

// latestPfConfBackup returns the most-recent /etc/pf.conf.backup.YYYYMMDDHHMMSS, or "".
func latestPfConfBackup() string {
	entries, err := filepath.Glob("/etc/pf.conf.backup.*")
	if err != nil || len(entries) == 0 {
		return ""
	}
	// filepath.Glob returns lexicographically sorted entries; the last has the
	// highest timestamp (YYYYMMDDHHMMSS sorts correctly as a string).
	return entries[len(entries)-1]
}

// stripPfAnchorLines rewrites pfConf with the agent anchor stanza removed.
func stripPfAnchorLines(ui *UI, r *Runner, pfConf string, data []byte) {
	var kept []string
	for _, line := range strings.Split(string(data), "\n") {
		if strings.Contains(line, `anchor "agent"`) ||
			strings.Contains(line, `load anchor "agent"`) ||
			strings.TrimSpace(line) == "# Claude Code sandbox user blocklist" {
			continue
		}
		kept = append(kept, line)
	}
	cleaned := strings.TrimRight(strings.Join(kept, "\n"), "\n") + "\n"
	if err := r.SudoWriteFile("strip agent anchor lines from pf.conf", pfConf, cleaned); err != nil {
		ui.WarnMsg(fmt.Sprintf("Could not update %s: %v", pfConf, err))
	} else {
		ui.Ok("Removed agent anchor lines from /etc/pf.conf")
	}
}

// pfctlLoadRules runs "sudo pfctl -f /etc/pf.conf", capturing stderr so
// parse errors are surfaced rather than silently swallowed.
func pfctlLoadRules() error {
	cmd := newSudoCommand(hostPfctlPath, "-f", "/etc/pf.conf")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg == "" {
			return err
		}
		return fmt.Errorf("%s", msg)
	}
	return nil
}

// launchctlBootstrap runs "sudo launchctl bootstrap system <plist>".
// Treats "already loaded" as success so the step stays idempotent.
func launchctlBootstrap(plist string) error {
	cmd := newSudoCommand(hostLaunchctlPath, "bootstrap", "system", plist)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := stderr.String()
		// "Bootstrap failed: 5: Input/output error" = service already loaded
		if strings.Contains(msg, "Bootstrap failed: 5") ||
			strings.Contains(msg, "already loaded") ||
			strings.Contains(msg, "service already exists") {
			return nil
		}
		return fmt.Errorf("launchctl bootstrap: %s", strings.TrimSpace(msg))
	}
	return nil
}
