//go:build hazmat_debug

package hazmat

// traceDebugConfigured is generated by scripts/configure-debug-trace.sh after
// platform trace prerequisites pass. A raw hazmat_debug build must fail closed.
var _ = traceDebugConfigured
