// sandbox-launch is the narrow privileged helper that bridges the dr→agent
// privilege gap for 'sandbox claude', 'sandbox shell', and 'sandbox exec'.
//
// It is the sole binary covered by the NOPASSWD sudoers rule:
//
//	dr ALL = (agent) NOPASSWD: /usr/local/libexec/sandbox-launch
//
// Unlike granting NOPASSWD to /usr/bin/sandbox-exec directly, this helper:
//   - Accepts only -f <policy-file> (no -p inline policies, no -D parameters)
//   - Validates the policy file is at /private/tmp/sandbox-<pid>.sb
//   - Validates the policy file is owned by the invoking user (SUDO_UID),
//     not by root or agent, to prevent pre-planted policy substitution
//   - Validates the policy file has mode 0644
//
// Usage (called by runAgentSeatbeltScript):
//
//	sudo -u agent /usr/local/libexec/sandbox-launch <policy-file> <cmd> [args...]
//
// Execs:
//
//	/usr/bin/sandbox-exec -f <policy-file> <cmd> [args...]
package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"syscall"
)

// policyFilePattern enforces that the policy file lives under /private/tmp
// and follows the sandbox-<pid>.sb naming convention.  The numeric PID
// component prevents traversal attacks (/private/tmp/../../etc/...).
var policyFilePattern = regexp.MustCompile(`^/private/tmp/sandbox-\d+\.sb$`)

// denyDefaultMarker is the literal string that every legitimate session policy
// generated by sandbox's generateSBPL starts with.  Policies that lack it
// (e.g. hand-written "(version 1)(allow default)" files) are rejected.
// This closes the "write a permissive policy file and get free arbitrary
// agent execution" path while still allowing all normal session policies.
const denyDefaultMarker = "(deny default)"

func main() {
	if len(os.Args) < 3 {
		die("usage: sandbox-launch <policy-file> <cmd> [args...]")
	}

	policyFile := os.Args[1]
	cmdArgs := os.Args[2:]

	if err := validatePolicyFile(policyFile); err != nil {
		die("sandbox-launch: %v", err)
	}

	// Build the sandbox-exec argv.  -f is the only flag we accept — no -p, no -D.
	argv := make([]string, 0, 3+len(cmdArgs))
	argv = append(argv, "/usr/bin/sandbox-exec", "-f", policyFile)
	argv = append(argv, cmdArgs...)

	if err := syscall.Exec(argv[0], argv, os.Environ()); err != nil {
		die("sandbox-launch: exec: %v", err)
	}
}

func validatePolicyFile(path string) error {
	// ── Path ──────────────────────────────────────────────────────────────────
	if !policyFilePattern.MatchString(path) {
		return fmt.Errorf("policy file must match /private/tmp/sandbox-<pid>.sb, got %q", path)
	}

	// ── Existence and metadata ────────────────────────────────────────────────
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("stat %q: %w", path, err)
	}

	// ── Ownership: must be SUDO_UID (the invoking dr user), not root/agent ─────
	//
	// SUDO_UID is set by sudo to the real UID of the invoking user.  If it is
	// absent or 0 the invocation is not coming through sudo as expected.
	sudoUID, err := strconv.Atoi(os.Getenv("SUDO_UID"))
	if err != nil || sudoUID == 0 {
		return fmt.Errorf("SUDO_UID not set or root — not a valid sudo invocation")
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return fmt.Errorf("cannot inspect policy file ownership")
	}
	if int(stat.Uid) != sudoUID {
		return fmt.Errorf("policy file owner uid %d does not match invoking user uid %d",
			stat.Uid, sudoUID)
	}

	// ── Mode: must be exactly 0644 ────────────────────────────────────────────
	//
	// runAgentSeatbeltScript writes with 0o644 then explicitly chmods to 0644
	// (overriding any process umask).  A different mode indicates the file was
	// not produced by the sandbox CLI.
	if perm := info.Mode().Perm(); perm != 0o644 {
		return fmt.Errorf("policy file has mode %04o, expected 0644", perm)
	}

	// ── Content: must start with deny-default ────────────────────────────────
	//
	// Read the first 512 bytes — enough to reach "(deny default)" in any
	// normal session policy and cheap to read.  Reject any policy that lacks
	// the marker, which catches "(allow default)" bypass attempts.
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open %q: %w", path, err)
	}
	head := make([]byte, 512)
	n, _ := f.Read(head)
	f.Close()
	if !bytes.Contains(head[:n], []byte(denyDefaultMarker)) {
		return fmt.Errorf("policy file does not contain %q — permissive policies are not allowed", denyDefaultMarker)
	}

	return nil
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
