package main

import (
	"fmt"
	"os"
	"sync/atomic"
	"testing"
)

// testFileSeq generates unique numeric suffixes so concurrent/sequential
// subtests can each own a distinct /private/tmp/sandbox-<n>.sb path.
var testFileSeq atomic.Int64

// writePolicyFile creates /private/tmp/sandbox-<seq>.sb with the given
// content and mode.  The path satisfies policyFilePattern.
func writePolicyFile(t *testing.T, content string, mode os.FileMode) string {
	t.Helper()
	seq := testFileSeq.Add(1)
	path := fmt.Sprintf("/private/tmp/sandbox-%d.sb", seq)
	if err := os.WriteFile(path, []byte(content), mode); err != nil {
		t.Fatalf("write policy file: %v", err)
	}
	// Explicit chmod so the mode is exactly what we asked for regardless of
	// the process umask — mirrors what runAgentSeatbeltScript does.
	if err := os.Chmod(path, mode); err != nil {
		t.Fatalf("chmod policy file: %v", err)
	}
	t.Cleanup(func() { os.Remove(path) })
	return path
}

// ── Path pattern ──────────────────────────────────────────────────────────────

func TestValidatePolicyFile_PathPattern(t *testing.T) {
	tests := []struct {
		path    string
		wantErr bool
	}{
		{"/private/tmp/sandbox-1234.sb", false},
		{"/private/tmp/sandbox-99999.sb", false},
		{"/private/tmp/sandbox-abc.sb", true},              // non-numeric
		{"/tmp/sandbox-1234.sb", true},                     // wrong dir (symlink target)
		{"/private/tmp/evil/../sandbox-1234.sb", true},     // traversal
		{"/private/tmp/sandbox-.sb", true},                 // empty PID component
		{"/private/tmp/xsandbox-1234.sb", true},            // wrong prefix
	}
	for _, tc := range tests {
		got := policyFilePattern.MatchString(tc.path)
		if tc.wantErr && got {
			t.Errorf("path %q: expected pattern to NOT match, but it did", tc.path)
		}
		if !tc.wantErr && !got {
			t.Errorf("path %q: expected pattern to match, but it did not", tc.path)
		}
	}
}

// ── Content check ─────────────────────────────────────────────────────────────

const (
	goodPolicy  = ";; Generated by sandbox\n(version 1)\n(deny default)\n(allow process-fork)\n"
	badPolicy   = "(version 1)\n(allow default)\n"
	emptyPolicy = ""
)

func TestValidatePolicyFile_ContentCheck(t *testing.T) {
	// Set SUDO_UID so the ownership check sees us as the invoking user.
	t.Setenv("SUDO_UID", fmt.Sprint(os.Getuid()))

	t.Run("deny-default passes", func(t *testing.T) {
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err != nil {
			t.Errorf("unexpected error for good policy: %v", err)
		}
	})

	t.Run("allow-default rejected", func(t *testing.T) {
		path := writePolicyFile(t, badPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for allow-default policy, got nil")
		}
	})

	t.Run("empty policy rejected", func(t *testing.T) {
		path := writePolicyFile(t, emptyPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for empty policy, got nil")
		}
	})

	t.Run("wrong mode rejected", func(t *testing.T) {
		path := writePolicyFile(t, goodPolicy, 0o600)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for 0600 mode, got nil")
		}
	})
}

// ── Ownership check ───────────────────────────────────────────────────────────

func TestValidatePolicyFile_OwnershipCheck(t *testing.T) {
	t.Run("matching SUDO_UID passes", func(t *testing.T) {
		t.Setenv("SUDO_UID", fmt.Sprint(os.Getuid()))
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err != nil {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("wrong SUDO_UID rejected", func(t *testing.T) {
		if os.Getuid() == 9999 {
			t.Skip("running as uid 9999")
		}
		t.Setenv("SUDO_UID", "9999")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for mismatched SUDO_UID, got nil")
		}
	})

	t.Run("missing SUDO_UID rejected", func(t *testing.T) {
		t.Setenv("SUDO_UID", "")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for missing SUDO_UID, got nil")
		}
	})

	t.Run("root SUDO_UID rejected", func(t *testing.T) {
		t.Setenv("SUDO_UID", "0")
		path := writePolicyFile(t, goodPolicy, 0o644)
		if err := validatePolicyFile(path); err == nil {
			t.Error("expected error for SUDO_UID=0, got nil")
		}
	})
}
